### PR TITLE
Fix #2598 sanitize leak

### LINKED ISSUE #2598: [BUG] detected memory leaks in trav_token_add hdf5/tools/lib/h5trav.c
detected memory leaks in trav_token_add hdf5/tools/lib/h5trav.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013581/pov.zip)

Stack trace:
```
==1947202==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x4c1a88 in realloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:164:3
#1 0x558111 in trav_token_add hdf5/tools/lib/h5trav.c:124:33
Indirect leak of 2 byte(s) in 1 object(s) allocated from:
#0 0x43bc77 in strdup /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cpp:452:3
#1 0x558177 in trav_token_add hdf5/tools/lib/h5trav.c:130:31
SUMMARY: AddressSanitizer: 26 byte(s) leaked in 2 allocation(s).
```

### PR DESCRIPTION
**Pull request by byrnHDF**

### CODE REVIEW

**Review by derobins — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

File: tools/lib/h5trav.c [hunk 1]
```diff
@@ -281,13 +281,13 @@ traverse(hid_t file_id, const char *grp_name, hbool_t visit_start, hbool_t recur
...
-                H5TOOLS_GOTO_ERROR((-1), "H5Lvisit_by_name failed");
+                H5TOOLS_ERROR((-1), "H5Lvisit_by_name failed");
         } /* end if */
         else {
             /* Iterate over links in group */
             if (H5Literate_by_name2(file_id, grp_name, trav_index_by, trav_index_order, NULL, traverse_cb,
                                     &udata, H5P_DEFAULT) < 0)
-                H5TOOLS_GOTO_ERROR((-1), "H5Literate_by_name failed");
+                H5TOOLS_ERROR((-1), "H5Literate_by_name failed");
         } /* end else */
```
Comment (derobins) [inline tools/lib/h5trav.c:291]: This will continue the traversal, even if there was an iteration problem, which I think is better than immediately jumping to the error condition. In the latter case, we could have moved the cleanup to after the done target.
