### PR TITLE
Test and document path handling of H5Lcreate_* API

### LINKED ISSUE #3827: H5Lcreate_soft succeeds despite link_name being a path
**Describe the bug**
The [latest docs](https://docs.hdfgroup.org/hdf5/develop/group___h5_l.html#ga894444623b58ce1ac3bd35538245ac78) for `H5Lcreate_soft` say that "`link_name` is interpreted relative to `link_loc_id` and must contain only the name of the soft link; link_name may not contain any additional path elements." However, creating a soft link with a path for `link_name` containing intermediate groups succeeds.

**Expected behavior**
If attempting to create a soft link with a `link_name` that contains additional path elements, the request should fail. 
Or, if this is the intended behavior, the documentation should be updated to say that `link_name` can contain path elements, and will be interpreted from root if it is an absolute path. 

**Platform**
 - HDF5 1.14.3
 - Ubuntu debian 22.04
 - gcc 11.3.0
 - CMake 3.22.1

**Replication**

```
herr_t print_name_op(hid_t grp, const char *name, const H5L_info2_t *info, void *op_data) {
  printf("Visited %s\n", name);
  return 0;
}

int main() {
  hid_t file_id = H5Fcreate("groups.1.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
  hid_t group_id = H5Gcreate(file_id, "grp1", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
  hid_t group_id2 = H5Gcreate(group_id, "grp2", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);

  if (H5Lcreate_soft("/", group_id, "/grp1/grp2/././soft_link_by_abs_path", H5P_DEFAULT, H5P_DEFAULT) < 0) {
    printf("Link create failed!");
    exit(1);
  }

  if (H5Lvisit2(file_id, H5_INDEX_NAME, H5_ITER_INC, print_name_op, NULL) < 0) {
    printf("Link visit failed!");
    exit(1);
  }

  H5Gclose(group_id2);
  H5Gclose(group_id);
  H5Fclose(file_id);
  return 0;
}
```

Output:
```
Visited grp1
Visited grp1/grp2
Visited grp1/grp2/soft_link_by_abs_path
```

### PR DESCRIPTION
**Pull request by mattjala**
The docs incorrectly say that `H5Lcreate_soft` can't take a path as its link name, and don't mention absolute path handling in any of the `H5Lcreate_*` documentation.

Fix #3827.

### CODE REVIEW

**Review by byrnHDF — APPROVED** [review]

File: src/H5Lpublic.h [hunk 1]
```diff
@@ -321,8 +322,8 @@ H5_DLL herr_t H5Lcreate_hard_async(hid_t cur_loc_id, const char *cur_name, hid_t
  *
  *          \p link_loc_id and \p link_name specify the location and name,
  *          respectively, of the new soft link. \p link_name is interpreted
- *          relative to \p link_loc_id and must contain only the name of the soft
- *          link; \p link_name may not contain any additional path elements.
+ *          as a path relative to \p link_loc_id, or an absolute path if it
+ *          begins with \c /.
```
Comment (fortnern) [inline src/H5Lpublic.h]: Maybe say something about how the actual name of the link created is only the last element of the path, and prior elements are used to find the group in which to create the link.

File: src/H5Lpublic.h [hunk 2]
```diff
@@ -1190,7 +1191,9 @@ H5_DLL herr_t H5Lvisit_by_name2(hid_t loc_id, const char *group_name, H5_index_t
  *          named \p link_name at the location specified in \p link_loc_id with
  *          user-specified data \p udata.
  *
- *          \p link_name is interpreted relative to \p link_loc_id.
+ *          \p link_name is interpreted relative to \p link_loc_id. If
+ *          \p link_name begins with \c \, then it will be interpreted as
+ *          an absolute path in the file.
```
Comment (fortnern) [inline src/H5Lpublic.h]: Same

File: src/H5Lpublic.h [hunk 3]
```diff
@@ -260,9 +260,10 @@ H5_DLL herr_t H5Lcopy(hid_t src_loc, const char *src_name, hid_t dst_loc, const
  *          location and name, respectively, of the new hard link.
  *
  *          \p cur_name and \p dst_name are interpreted relative to \p cur_loc
- *          and \p dst_loc, respectively. If \p cur_loc and \p dst_loc are the
- *          same location, the HDF5 macro #H5L_SAME_LOC can be used for either
- *          parameter (but not both).
+ *          and \p dst_loc, respectively. If a given name begins with \c \,
+ *          then it will be interpreted as absolute path in the file. If
```
Comment (fortnern) [inline src/H5Lpublic.h]: Same

**Comment by mattjala** [comment]
Added tests in `links.c` that all link creation functions correctly handle relative and absolute paths as provided link names.

File: test/links.c [hunk 4]
```diff
@@ -22623,6 +22623,253 @@ timestamps(hid_t fapl)
...
+        H5Gclose(grp1);
+        H5Gclose(grp2);
+        H5Fclose(file_id);
+    }
+    H5E_END_TRY
+    return FAIL;
+}
+
+/*-------------------------------------------------------------------------
+ * Function:    ext_link_path_handling
```
Comment (jhendersonHDF) [inline test/links.c]: ud_link_path_handling

**Review by jhendersonHDF — APPROVED** [review]
Minor comment; otherwise looks good

**Review by fortnern — APPROVED** [review]
