### PR TITLE
Increased H5FD_ROS3_MAX_SECRET_TOK_LEN to 4096 to accommodate long AWS secret tokens

### LINKED ISSUE #4063: The value of H5FD_ROS3_MAX_SECRET_TOK_LEN is too small
**Describe the bug**
The AWS STS routinely issues secret tokens that are longer than 1024 bytes. The value of H5FD_ROS3_MAX_SECRET_TOK_LEN is set at 1024, hence long secret tokens do not get added to the authorization headers.
 
**Platform (please complete the following information)**

The limitation is resent in the HEAD of the develop branch as 2024/03/04

### PR DESCRIPTION
**Pull request by aivazis**
Increased H5FD_ROS3_MAX_SECRET_TOK_LEN to 4096 to allow long AWS secret tokens to be included in the authorization headers.

While walking through the code in `H5FDros3` and `H5FDs3comms`, i bumped into some stuff, so i made the following tiny improvements:

- use the macro H5FD_ROS3_MAX_SECRET_TOK_LEN when allocating temporary buffers for constructing the headers, rather than a 1024 literal
- corrected the use of a dangling pointer when printing out host stats
- fixed some bad format specifiers
- stratified DEBUG_LEVEL into multiple values to allow for finer control over what gets printed out during debugging

Closes #4063

### CODE REVIEW

**Review by mattjala — APPROVED** [review]

File: src/H5FDs3comms.c [hunk 1]
```diff
@@ -47,9 +47,14 @@
...
-/* toggle debugging (enable with 1)
+/* toggle debugging: pick a level
  */
-#define S3COMMS_DEBUG 0
+#define S3COMMS_DEBUG_NONE           0
+#define S3COMMS_DEBUG_REQUESTS       1
+#define S3COMMS_DEBUG_TRACE_API      2
+#define S3COMMS_DEBUG_TRACE_INTERNAL 3
+#define S3COMMS_DEBUG_HEADERS        4
+#define S3COMMS_DEBUG                S3COMMS_DEBUG_REQUESTS
```
Comment (jhendersonHDF) [inline src/H5FDs3comms.c]: Was the intention here to turn on comms debugging by default? We probably want all debugging off by default otherwise.

**Comment by jhendersonHDF** [comment]
The changes look fine to me and are a definite improvement, but I believe this might cause some large stack frame warnings in -Werror builds due to the usage of `H5FD_ROS3_MAX_SECRET_TOK_LEN` in a struct in `tools/lib/h5tools_utils.h`. I don't believe we currently have any -Werror builds where we are enabling support for the ROS3 VFD, so we may want to check this.

File: src/H5FDs3comms.c (hunk 1 above)
Comment (aivazis) [reply src/H5FDs3comms.c]: no. oversight on my part. i'll push a fix asap

Comment (aivazis) [reply src/H5FDs3comms.c]: thanks for catching it

**Comment by aivazis** [comment]
> The changes look fine to me and are a definite improvement, but I believe this might cause some large stack frame warnings in -Werror builds due to the usage of `H5FD_ROS3_MAX_SECRET_TOK_LEN` in a struct in `tools/lib/h5tools_utils.h`. I don't believe we currently have any -Werror builds where we are enabling support for the ROS3 VFD, so we may want to check this.

we may be able to get away with a smaller value for the maximum token length. i'll make another pass at the AWS documentation for a tighter limit.

**Comment by jhendersonHDF** [comment]
> we may be able to get away with a smaller value for the maximum token length. i'll make another pass at the AWS documentation for a tighter limit.

We should probably check first to see if this will even be an issue, but I'm also not a big fan of "large" arrays in structures anyway. We should probably rewrite the code a bit so we don't end up with that array on the stack.

File: src/H5FDs3comms.c [hunk 2]
```diff
@@ -1645,7 +1654,7 @@ H5FD_s3comms_aws_canonical_request(char *canonical_request_dest, int _cr_size, c
     size_t      sh_size      = (size_t)_sh_size;
     size_t      cr_len       = 0; /* working length of canonical request str */
     size_t      sh_len       = 0; /* working length of signed headers str */
-    char        tmpstr[1024];
+    char        tmpstr[H5FD_ROS3_MAX_SECRET_TOK_LEN];
```
Comment (derobins) [inline src/H5FDs3comms.c:1657]: I would allocate this dynamically.  4096 is probably big enough to start tripping our stack size warnings and we endeavor to be warning-free.

**Comment by derobins** [comment]
> > The changes look fine to me and are a definite improvement, but I believe this might cause some large stack frame warnings in -Werror builds due to the usage of `H5FD_ROS3_MAX_SECRET_TOK_LEN` in a struct in `tools/lib/h5tools_utils.h`. I don't believe we currently have any -Werror builds where we are enabling support for the ROS3 VFD, so we may want to check this.
> 
> we may be able to get away with a smaller value for the maximum token length. i'll make another pass at the AWS documentation for a tighter limit.

I would just allocate it dynamically and then it's a non-problem.

**Review by derobins — APPROVED** [review]
