### PR TITLE
Fixes gcc -15 warning message about potential null pointer dereference

### LINKED ISSUE #5780: GCC -15 warnings
/src/H5B.c:1437:46: warning: potential null pointer dereference [-Wnull-dereference]
 1437 |     if (*lt_key_changed && H5_addr_defined(bt->left)) {
src/H5private.h:440:36: note: in definition of macro ‘H5_addr_defined’
  440 | #define H5_addr_defined(X)       ((X) != HADDR_UNDEF)
      |                                    ^
src/H5B.c:1452:51: warning: potential null pointer dereference [-Wnull-dereference]
 1452 |     else if (*rt_key_changed && H5_addr_defined(bt->right)) {
src/H5private.h:440:36: note: in definition of macro ‘H5_addr_defined’
  440 | #define H5_addr_defined(X)       ((X) != HADDR_UNDEF)

### PR DESCRIPTION
**Pull request by brtnfld**
Fixes warning message indicating, for example, that the H5_addr_defined(bt->right)  macro might be evaluated with a null bt pointer..

Fixes #5780 

----

> [!IMPORTANT]
> Add null pointer check in `H5B__remove_helper()` in `H5B.c` to prevent potential null pointer dereference warnings from GCC.
> 
>   - **Behavior**:
>     - Add null pointer check for `bt` in `H5B__remove_helper()` in `H5B.c` to prevent potential null pointer dereference when evaluating `H5_addr_defined(bt->left)` and `H5_addr_defined(bt->right)`.
>   - **Misc**:
>     - Fixes GCC warning about potential null pointer dereference.
>     - Addresses issue #5780.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=HDFGroup%2Fhdf5&utm_source=github&utm_medium=referral)<sup> for e18867431ba495dcc21b1392f64a5006dfbcf6bb. You can [customize](https://app.ellipsis.dev/HDFGroup/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/H5B.c [hunk 1]
```diff
@@ -1434,7 +1434,7 @@ H5B__remove_helper(H5F_t *f, haddr_t addr, const H5B_class_t *type, int level, u
         ret_value = H5B_INS_NOOP;
 
     /* Patch keys in neighboring trees if necessary */
-    if (*lt_key_changed && H5_addr_defined(bt->left)) {
+    if (*lt_key_changed && bt != NULL && H5_addr_defined(bt->left)) {
```
Comment (jhendersonHDF) [inline src/H5B.c:1437]: I'm guessing GCC is warning about line 1354 above where `bt` can get set to NULL, but I guess we don't currently exercise that case in testing?

Comment (brtnfld) [reply src/H5B.c:1437]: I would assume that leads to the warning. I'm guessing that is not tested

**Review by hyoklee — APPROVED** [review]

**Review by bmribler — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]
