### PR TITLE
Make test/evict_on_close.c FILENAMES static

### LINKED ISSUE #5988: Make  test/evict_on_close.c `FILENAMES` static
gcc-13.3.0 linker fails on Haiku OS.

```
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld:
final link failed: bad value
```

### PR DESCRIPTION
**Pull request by hyoklee**
close #5988 

----

> [!IMPORTANT]
> Make `FILENAMES` array static in `test/evict_on_close.c` to limit its scope.
> 
>   - **Code Changes**:
>     - Make `FILENAMES` array `static` in `test/evict_on_close.c` to limit its scope to the file.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=HDFGroup%2Fhdf5&utm_source=github&utm_medium=referral)<sup> for b69e6c27fe9f718a82989d167e1a95457b1836c2. You can [customize](https://app.ellipsis.dev/HDFGroup/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by jhendersonHDF — APPROVED** [review]

File: test/evict_on_close.c [hunk 1]
```diff
@@ -36,8 +36,8 @@
 /* (Requires debug build of the library) */
 /* #define EOC_MANUAL_INSPECTION */
 
-const char *FILENAMES[] = {"evict-on-close", /* 0 */
-                           NULL};
+static const char *FILENAMES[] = {"evict-on-close", /* 0 */
+                                  NULL};
```
Comment (glennsong09) [inline test/evict_on_close.c:40]: Looks like it added some whitespace. Is that okay?

**Review by glennsong09 — APPROVED** [review]
