### PR TITLE
Fix display of '--' options in documentation

### LINKED ISSUE #6307: Tools docs: Unwanted conversion of double minus sign
CORRECTED MESSAGE.  This problem occurs in Tools docs, not install docs.

In **command line tool docs**, such as [h5dump documentation](https://support.hdfgroup.org/documentation/hdf5/latest/_h5_t_o_o_l__d_p__u_g.html), double minus signs are used extensively for command line options.  Example:  `h5dump --version`.

~In the newly converted "2.1.1" markdown docs, many of these double minus signs are seeing unexpected conversion into a single Unicode n-dash, when viewed in an ordinary web browser.  I am seeing this in GitHub "Preview" mode when trying to read the install docs in my browser (Safari on Mac).  I speculate that GitHub itself is doing this conversion when rendering web pages, and is independent of the browser, but not sure.~

In these **tools docs**, many of these double minus signs are seeing unexpected conversion into a single Unicode n-dash, when viewed in an ordinary web browser.

These usages need to be somehow escaped or coded, such that they will render correctly as simple double minus signs in the ordinary browser.  In particular this is needed for cutting and pasting commands.  A pasted n-dash will result in a command error.  Old hacks like me can usually recognize this confusion fairly quickly, but this can be troublesome for less experienced users.

I find other pages in support docs that are rendering many double minus signs correctly, but I am not sure how they do it.  Escaping as code excerpts is one way.  I am not a markdown expert.  I suspect that there might be a markdown behavior that treats double minus signs differently if they are at the start of a new line; which is where I first noticed this problem.

Please fix the rendered double minus signs, when you can get to it.  Thanks.

### PR DESCRIPTION
**Pull request by jhendersonHDF**
@Dave-Allured

### CODE REVIEW

File: tools/src/h5dump/h5dump.h [hunk 1]
```diff
@@ -23,96 +23,91 @@
...
- * \li <strong>--xml</strong>          Output in XML using Schema
- * \li <strong>--use-dtd</strong>      Output in XML using DTD
- * \li <strong>--xml-dtd=U</strong>    Use the DTD or schema at U
- * \li <strong>--xml-ns=S</strong>     (XML Schema) Use qualified names n the XML
+ * \li <strong>\--xml</strong>          Output in XML using Schema
+ * \li <strong>\--use-dtd</strong>      Output in XML using DTD
+ * \li <strong>\--xml-dtd=U</strong>    Use the DTD or schema at U
+ * \li <strong>\--xml-ns=S</strong>     (XML Schema) Use qualified names in the XML.
  *                                       ":": no namespace, default: "hdf5:"
- *                                       E.g., to dump a file called "-f", use h5dump -- -f
```
Comment (jhendersonHDF) [inline tools/src/h5dump/h5dump.h:115]: This part was incorrectly brought over from the old h5dump docs. Restored the original text below under the "Option Argument Conventions" section.

**Comment by Dave-Allured** [comment]
@jhendersonHDF  Nice.  Thanks for quick response.  I did not do a full review.

File: tools/src/h5dump/h5dump.h [hunk 2]
```diff
@@ -23,96 +23,91 @@
...
- * <strong>--vol-name</strong>  Name of the VOL connector to use for opening the HDF5 file specified \li
- * <strong>--vol-info</strong>  VOL-specific info to pass to the VOL connector used for opening the HDF5 file
- * specified.<br /> If none of the above options are used to specify a VOL, then the VOL named by \b
- * HDF5_VOL_CONNECTOR (or the native VOL connector, if that environment variable is unset) will be used
- * \li<strong>--vfd-value</strong> Value (ID) of the VFL driver to use for opening the HDF5 file specified
- * \li <strong>--vfd-name</strong> Name of the VFL driver to use for opening the HDF5 file specified
- * \li <strong>--vfd-info</strong> VFD-specific info to pass to the VFL driver used for
+ * \li <strong>\--contents</strong>   Print a list of the file contents, group and dataset,
+ *              names and values, then exit. Optional value 1 also prints attributes,
+ * <code>\--contents=1</code>. \li <strong>\--superblock</strong> Print the content of the super block \li
```
Comment (brtnfld) [inline tools/src/h5dump/h5dump.h]: Looks like the formatting is messed-up

Comment (jhendersonHDF) [reply tools/src/h5dump/h5dump.h]: Hmm yes, clang might have done that. I'll fix it

File: doxygen/dox/hdf5_1_8.dox [hunk 3]
```diff
@@ -296,13 +296,13 @@ The following wrappers were added to the class H5::ObjCreatPropList for the resp
...
+<code>\--enable-threadsafe</code> and <code>\--enable-hl</code> are combined unless additional options
 are specified (see below). Since the high-level library is built by default, this means that these
-extra configuration options will need to be used any time <code>--enable-threadsafe</code> is selected.
+extra configuration options will need to be used any time <code>\--enable-threadsafe</code> is selected.
 
-To use Autotools to build an application with --enable-threadsafe, use one of the following approaches:
-\li Use <code>--disable-h</code>l to disable the high-level library. (Recommended)
-\li Use <code>--enable-unsupported</code> to build the high-level library with the thread-safety feature.
+To use Autotools to build an application with \--enable-threadsafe, use one of the following approaches:
+\li Use <code>\--disable-h</code>l to disable the high-level library. (Recommended)
```
Comment (brtnfld) [inline doxygen/dox/hdf5_1_8.dox]: `l`  is outside

File: doxygen/dox/hdf5_1_8.dox [hunk 4]
```diff
@@ -296,13 +296,13 @@ The following wrappers were added to the class H5::ObjCreatPropList for the resp
...
-<code>--enable-threadsafe</code> and <code>--enable-hl</code> are combined unless additional options
+<code>\--enable-threadsafe</code> and <code>\--enable-hl</code> are combined unless additional options
 are specified (see below). Since the high-level library is built by default, this means that these
-extra configuration options will need to be used any time <code>--enable-threadsafe</code> is selected.
+extra configuration options will need to be used any time <code>\--enable-threadsafe</code> is selected.
 
-To use Autotools to build an application with --enable-threadsafe, use one of the following approaches:
-\li Use <code>--disable-h</code>l to disable the high-level library. (Recommended)
-\li Use <code>--enable-unsupported</code> to build the high-level library with the thread-safety feature.
+To use Autotools to build an application with \--enable-threadsafe, use one of the following approaches:
```
Comment (brtnfld) [inline doxygen/dox/hdf5_1_8.dox]: some parameters have` <code> </code>` some don't

Comment (jhendersonHDF) [reply doxygen/dox/hdf5_1_8.dox]: I mostly left what was there and just did a find/replace, but I can fix ones I find or that are pointed out

File: tools/src/h5repack/h5repack.h [hunk 5]
```diff
@@ -29,73 +29,73 @@
...
- * \li <strong>--layout=LAYT</strong>   Layout type
- * \li <strong>--fs_strategy=FS_STRATEGY</strong>  File space management strategy for
+ * \li <strong>\--merge</strong>          Follow external soft link recursively and merge data
+ * \li <strong>\--prune</strong>          Do not follow external soft links and remove link
+ * \li <strong>\--merge \--prune</strong>  Follow external link, merge data and remove dangling link
+ * \li <strong>\--compact=L1</strong>    Maximum number of links in header messages
+ * \li <strong>\--indexed=L2</strong>    Minimum number of links in the indexed format
+ * \li <strong>\--ssize=S[:F]</strong>   Shared object header message minimum size
+ * \li <strong>\--minimum=M</strong>     Do not apply the filter to datasets smaller than M
+ * \li <strong>\--file=E</strong>        Name of file E with the \--file and \--layout options
```
Comment (brtnfld) [inline tools/src/h5repack/h5repack.h]: --file should be wrapped in strong

File: tools/src/h5diff/h5diff_main.h
Comment (jhendersonHDF) [inline tools/src/h5diff/h5diff_main.h:1]: clang-format had formatted this file, I cleaned it up a little

File: tools/src/h5dump/h5dump.h [hunk 6]
```diff
@@ -12,6 +12,7 @@
 #ifndef H5DUMP_H
 #define H5DUMP_H
 
+/* clang-format off */
```
Comment (jhendersonHDF) [inline tools/src/h5dump/h5dump.h:15]: clang-format won't leave this file alone

**Review by brtnfld — DISMISSED** [review]

File: doxygen/dox/hdf5_1_8.dox [hunk 7]
```diff
@@ -1162,20 +1162,20 @@ a value or name difference between two attributes, subsequent attributes were no
 Configure now generates Makefiles that build in silent make mode by default. In this mode,
 compile and link lines are significantly simplified for clarity. You can opt out of this
 default with either of the following approaches:
-\li Use the <code>--disable-silent-rules flag</code> at configure time to override the default and view actual
+\li Use the <code>\--disable-silent-rules flag</code> at configure time to override the default and view actual
```
Comment (brtnfld) [inline doxygen/dox/hdf5_1_8.dox]: "flag" inside `<code>` tag

File: tools/src/misc/h5mkgrp.h [hunk 8]
```diff
@@ -26,29 +26,29 @@
  *  <h4>h5mkgrp [OPTIONS] FILE GROUP</h4>
  *
  * \subsection subsec_cltools_h5mkgrp_error Error Report Option
- * \li<strong>--enable-error-stack</strong> Prints messages from the HDF5 error stack as they occur.
- *            Optional value 2 also prints file open errors, --enable-error-stack=2.
+ * \li<strong>\--enable-error-stack</strong> Prints messages from the HDF5 error stack as they occur.
```
Comment (brtnfld) [inline tools/src/misc/h5mkgrp.h]: missing space after` \li`

File: tools/src/h5dump/h5dump.h [hunk 9]
```diff
@@ -23,96 +24,95 @@
...
+ *                                              <strong>\--filedriver=hdfs</strong>
+ *                                              \code <attrs> :: (<namenode name>,<namenode port>, <kerberos cache path>,<username>, <buffer size>) \endcode
+ *                                              Any absent attribute will use a default value.
+ * \li <strong>\--vol-value</strong> Value (ID) of the VOL connector to use for opening the HDF5 file specified
+ * \li <strong>\--vol-name</strong>  Name of the VOL connector to use for opening the HDF5 file specified
+ * \li <strong>\--vol-info</strong>  VOL-specific info to pass to the VOL connector used for opening the HDF5 file specified.<br />
+ *                                   If none of the above options are used to specify a VOL, then the VOL named by
+ *                                   \b HDF5_VOL_CONNECTOR (or the native VOL connector, if that environment variable
+ *                                   is unset) will be used
+ * \li<strong>\--vfd-value</strong> Value (ID) of the VFL driver to use for opening the HDF5 file specified
```
Comment (brtnfld) [inline tools/src/h5dump/h5dump.h]: missing space after `\li`

File: tools/src/h5dump/h5dump.h [hunk 10]
```diff
@@ -122,21 +122,24 @@
  * The \b STRIDE, \b COUNT, and \b BLOCK parameters are optional and will default to 1 in
  * each dimension. \b START is optional and will default to 0 in each dimension.
  *
- * \li <strong>--start=START</strong>    Offset of start of subsetting selection
+ * \li <strong>\--start=START</strong>    Offset of start of subsetting selection
  *  \b START - is a list of integers, the number of which are equal to the
  *      number of dimensions in the dataspace being queried.<br />
- * \li <strong>--stride=STRIDE</strong>  Hyperslab stride
+ * \li <strong>\--stride=STRIDE</strong>  Hyperslab stride
```
Comment (brtnfld) [inline tools/src/h5dump/h5dump.h:130]: Swapped --stride/--count descriptions (pre-existing)

\li \--stride=STRIDE  Hyperslab stride
    COUNT - is a list of integers...     ← should say STRIDE
\li \--count=COUNT    Number of blocks to include in selection
    STRIDE - is a list of integers...    ← should say COUNT

The description bodies are swapped. Not introduced by this PR, but worth fixing since the file is already being edited.

File: tools/src/h5dump/h5dump.h [hunk 11]
```diff
@@ -23,96 +24,95 @@
...
- * \li <strong>--vfd-name</strong> Name of the VFL driver to use for opening the HDF5 file specified
- * \li <strong>--vfd-info</strong> VFD-specific info to pass to the VFL driver used for
+ * \li <strong>\--contents</strong>   Print a list of the file contents, group and dataset,
+ *              names and values, then exit. Optional value 1 also prints attributes, <code>\--contents=1</code>.
+ * \li <strong>\--superblock</strong> Print the content of the super block
+ * \li <strong>\--header</strong>     Print the header only; no data is displayed
+ * \li <strong>\--filedriver=D</strong> Specify which driver to open the file with
+ * \li <strong>\--output=F</strong>   Output raw data into file F
+ * \li <strong>\--binary=B</strong>   Binary file output, of form B
+ * \li <strong>\--ddl=F</strong>      Output ddl text into file F Use blank(empty) filename F to suppress ddl display
```
Comment (brtnfld) [inline tools/src/h5dump/h5dump.h]: "Use blank(empty) filename F to suppress ddl display" was on another line, if not, then you need a period after F

**Review by brtnfld — APPROVED** [review]

**Review by lrknox — APPROVED** [review]
