### PR TITLE
Deprecate the h5dump XML feature.

### LINKED ISSUE #2646: h5dump uses `DEFAULT_XSD` and `DEFAULT_DTD`that do not exist.
**Describe the bug**
See attached screen shot.

**Expected behavior**
The referenced files should exist.

Screen Shot 2023-03-28 at 12 10 33 PM

### PR DESCRIPTION
**Pull request by byrnHDF**
Closes #2646

### CODE REVIEW

File: tools/src/h5dump/h5dump.h [hunk 1]
```diff
@@ -193,6 +193,13 @@
  *
  *      h5dump --dataset=/foo --filedriver=family fam%05d.h5
  *
+ * \subsubsection subsubsec_cltools_h5dump_xml XML Deprecated
+ * The XML option for h5dump has been deprecated. The methods for displaying XML output
+ * has not been updated since 1.10.0 was released. Many new features introduced into the
+ * library have never been added to the XML generation functions. Also the dtd and xsd
+ * files for XML have been archived, and copies of the files, HDF5-File.dtd and HDF5-File.xsd,
+ * have been saved in the <source>/tools/test/h5dump/testfiles/xml folder.
```
Comment (mattjala) [inline tools/src/h5dump/h5dump.h]: CI is failing due to the <source> tag here

File: tools/test/h5dump/testfiles/xml/HDF5-File.dtd [hunk 2]
```diff
@@ -0,0 +1,306 @@
+<!--
```
Comment (mattjala) [inline tools/test/h5dump/testfiles/xml/HDF5-File.dtd:1]: Why are the dtd and xsd files included in this PR?

Comment (byrnHDF) [reply tools/test/h5dump/testfiles/xml/HDF5-File.dtd:1]: Because they keep getting lost! They are for reference if someone wants to inspect them.
Once the XML option is actually removed then everything will get removed.

**Review by mattjala — APPROVED** [review]
The i386 failure seems unrelated to the changes here.

**Review by hyoklee — APPROVED** [review]

**Review by lrknox — APPROVED** [review]
