### PR TITLE
Fix double-free issue in H5D__chunk_copy

### LINKED ISSUE #6123: h5repack crashes with double free when using --low
**Describe the bug**
Running h5repack with the --low compression option on a crafted HDF5 file causes the tool to abort due to a double free detected by the GNU C Library allocator.
The program terminates with:
free(): double free detected in tcache 2
SIGABRT

**Steps to Reproduce:**
The PoC attachment contains the input file that triggers the crash:

[PoC.zip](https://github.com/user-attachments/files/24281631/PoC.zip)

COMMAND LINE: ./h5repack --low 2 -v 2 Double_Free out.h5

**Expected behavior**
h5repack should handle malformed input gracefully and exit with an error message, rather than aborting due to a double free.

**Platform (please complete the following information)**
 - HDF5 version:
    Git develop branch
    commit: 441d83a8962ef3571f0969bf923186e2ac4dc8c4
 - OS and version:
   Ubuntu 18.04.6 LTS
 - Compiler and version:
   clang 14.0.6 (used via hfuzz-clang wrapper)
 - Build system (e.g. CMake version) and generator (e.g. XCode, Ninja):
   Build system: CMake 3.30.0
   Generator: default Unix Makefiles (via cmake -S . -B build)
 - Any configure options you specified:
   -DHDF5_BUILD_TOOLS=ON -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_TESTING=OFF -
    DHDF5_BUILD_HL_LIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -
    DCMAKE_BUILD_TYPE=RelWithDebInfo, compiler flags include -g -O2 -fsanitize-coverage=trace-pc-guard -
    finstrument-functions.
 - MPI library and version (parallel HDF5):
   Parallel HDF5 not enabled; no MPI library used.

**Additional context**

GDB output excerpt:
 group                                                    /
free(): double free detected in tcache 2

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6e367f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6e7f837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6faca7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e868ba in malloc_printerr (str=str@entry=0x7ffff6fae6e8 "free(): double free detected in tcache 2") at malloc.c:5342
#4  0x00007ffff6e8e0ed in _int_free (have_lock=0, p=0xa877fe0, av=0x7ffff71e1c40 <main_arena>) at malloc.c:4195
#5  __GI___libc_free (mem=0xa877ff0) at malloc.c:3134
#6  0x00000000006c30ba in H5MM_xfree (mem=0xa877ff0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MM.c:201
#7  H5MM_xfree_const (mem=0xa877ff0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MM.c:224
#8  0x0000000000575d53 in H5E__clear_entries (nentries=<optimized out>, estack=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Eint.c:1810
#9  H5E_clear_stack () at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Eint.c:1852
#10 0x0000000000631c2f in H5Gclose (group_id=group_id@entry=144115188075855874) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5G.c:868
#11 0x000000000043fded in do_copy_objects (fidin=fidin@entry=72057594037927936, fidout=fidout@entry=72057594037927937, travt=<optimized out>, options=options@entry=0xa809360)
    at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:1482
#12 0x0000000000437abf in copy_objects (
    fnamein=fnamein@entry=0x7fffffffe517 "/tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.e2e133389.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    fnameout=fnameout@entry=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:326
#13 0x000000000045d111 in h5repack (infile=0x7fffffffe517 "/tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.e2e133389.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    outfile=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack.c:53
#14 0x0000000000463ade in main (argc=<optimized out>, argv=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_main.c:1037
(gdb)

### LINKED ISSUE #6124: h5repack aborts due to double free when using -c with --enable-error-stack
**Describe the bug**
Running h5repack with compression enabled using -c 10 and --enable-error-stack on a crafted HDF5 file causes the tool to abort due to a double free detected by the GNU C Library allocator.
The program terminates with:
free(): double free detected in tcache 2
SIGABRT

**Steps to Reproduce:**
The PoC attachment contains the input file that triggers the crash:

[PoC.zip](https://github.com/user-attachments/files/24281661/PoC.zip)

COMMAND LINE: ./h5repack -c 10 --enable-error-stack Double_Free_2 out.h5

**Expected behavior**
h5repack should handle malformed input gracefully and exit with an error message, rather than aborting due to a double free.

**Platform (please complete the following information)**
 - HDF5 version:
   Git develop branch
  commit: 441d83a8962ef3571f0969bf923186e2ac4dc8c4
 - OS and version:
   Ubuntu 18.04.6 LTS
 - Compiler and version:
   clang 14.0.6 (used via hfuzz-clang wrapper)
 - Build system (e.g. CMake version) and generator (e.g. XCode, Ninja):
   Build system: CMake 3.30.0
   Generator: default Unix Makefiles (via cmake -S . -B build)
 - Any configure options you specified:
   -DHDF5_BUILD_TOOLS=ON -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_TESTING=OFF -
    DHDF5_BUILD_HL_LIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -
    DCMAKE_BUILD_TYPE=RelWithDebInfo, compiler flags include -g -O2 -fsanitize-coverage=trace-pc-guard -
    finstrument-functions.
 - MPI library and version (parallel HDF5):
   Parallel HDF5 not enabled; no MPI library used.

**Additional context**
GDB output excerpt:
  #018: /root/DriveSched/benchmarks/hdf5/hdf5/src/H5PB.c line 697 in H5PB_read(): read through metadata accumulator failed
    major: Page Buffering
    minor: Read failed
  #019: /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Faccum.c line 248 in H5F__accum_read(): unable to copy chunked storage
    major: Low-level I/O
    minor: Read failed
  #020: /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FDint.c line 260 in H5FD_read(): addr overflow, addr = 6040, size = 1835101741, eoa = 8088
    major: Invalid arguments to routine
    minor: Address overflowed
free(): double free detected in tcache 2

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6e367f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6e7f837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6faca7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e868ba in malloc_printerr (str=str@entry=0x7ffff6fae6e8 "free(): double free detected in tcache 2") at malloc.c:5342
#4  0x00007ffff6e8e0ed in _int_free (have_lock=0, p=0xa877c60, av=0x7ffff71e1c40 <main_arena>) at malloc.c:4195
#5  __GI___libc_free (mem=0xa877c70) at malloc.c:3134
#6  0x00000000006c30ba in H5MM_xfree (mem=0xa877c70) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MM.c:201
#7  H5MM_xfree_const (mem=0xa877c70) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MM.c:224
#8  0x0000000000575d53 in H5E__clear_entries (nentries=<optimized out>, estack=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Eint.c:1810
#9  H5E_clear_stack () at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Eint.c:1852
#10 0x000000000056b6ee in H5Epush2 (err_stack=1008806316530991104, file=0xb4bcf8 "/root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c",
    func=0xb4c3ce "do_copy_objects", line=1300, cls_id=864691128455135233, maj_id=936748722493063349, min_id=936748722493063350, fmt=0xb4c757 "H5Ocopy failed")
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5E.c:545
#11 0x000000000043ed28 in do_copy_objects (fidin=fidin@entry=72057594037927936, fidout=fidout@entry=72057594037927937, travt=0xa872670, options=options@entry=0xa809360)
    at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:1308
#12 0x0000000000437abf in copy_objects (
    fnamein=fnamein@entry=0x7fffffffe508 "/tmp/168_c_10_enable_error_stack/SIGABRT.PC.7ffff6e34e87.STACK.e2e133389.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    fnameout=fnameout@entry=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:326
#13 0x000000000045d111 in h5repack (
    infile=0x7fffffffe508 "/tmp/168_c_10_enable_error_stack/SIGABRT.PC.7ffff6e34e87.STACK.e2e133389.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    outfile=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack.c:53
#14 0x0000000000463ade in main (argc=<optimized out>, argv=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_main.c:1037
(gdb)

### LINKED ISSUE #6125: h5repack aborts due to heap corruption when using --low compression
**Describe the bug**
Running h5repack with the --low compression option on a crafted HDF5 file causes the tool to abort due to heap corruption, detected by the GNU C Library allocator.

**Steps to Reproduce:**
The PoC attachment contains the input file that triggers the crash:

[PoC.zip](https://github.com/user-attachments/files/24281684/PoC.zip)

COMMAND LINE: ./h5repack --low 2 -v 2 Heap_Corruption out.h5

**Expected behavior**
h5repack should handle malformed input gracefully and either reject the file or exit cleanly with an error message, rather than aborting due to heap corruption.

**Platform (please complete the following information)**
 - HDF5 version:
   Git develop branch
   441d83a8962ef3571f0969bf923186e2ac4dc8c4
 - OS and version:
   Ubuntu 18.04.6 LTS
 - Compiler and version:
   clang 14.0.6 (used via hfuzz-clang wrapper)
 - Build system (e.g. CMake version) and generator (e.g. XCode, Ninja):
   Build system: CMake 3.30.0
    Generator: default Unix Makefiles (via cmake -S . -B build)
 - Any configure options you specified:
   -DHDF5_BUILD_TOOLS=ON -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_TESTING=OFF -
    DHDF5_BUILD_HL_LIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -
    DCMAKE_BUILD_TYPE=RelWithDebInfo, compiler flags include -g -O2 -fsanitize-coverage=trace-pc-guard -
    finstrument-functions.
 - MPI library and version (parallel HDF5):
   Parallel HDF5 not enabled; no MPI library used.

**Additional context**
GDB output excerpt:
(gdb) r
Starting program: /root/DriveSched/benchmarks/hdf5/h5repack/h5repack --low 2 -v 2 /tmp/cbh_tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.19cfba42a6.CODE.-6.ADDR.0.INSTR.mov____0x108\(%rsp\),%rcx.fuzz out.h5
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Making new file ...

 Type     Filter (Compression)        Timing read/write    Name

 group                                                    /
 dset                         0.000000e+00/2.184017e-03   /dset
malloc_consolidate(): invalid chunk size

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6e367f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6e7f837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6faca7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e868ba in malloc_printerr (str=str@entry=0x7ffff6fae2d8 "malloc_consolidate(): invalid chunk size") at malloc.c:5342
#4  0x00007ffff6e86b5e in malloc_consolidate (av=av@entry=0x7ffff71e1c40 <main_arena>) at malloc.c:4471
#5  0x00007ffff6e8a848 in _int_malloc (av=av@entry=0x7ffff71e1c40 <main_arena>, bytes=bytes@entry=1992) at malloc.c:3713
#6  0x00007ffff6e8d0ac in __GI___libc_malloc (bytes=1992) at malloc.c:3067
#7  0x0000000000617b7f in H5FL__malloc (mem_size=1992) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FL.c:211
#8  H5FL_blk_malloc (head=head@entry=0xe21ba8 <H5_H5FS_bin_t_seq_free_list>, size=size@entry=1984) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FL.c:773
#9  0x000000000061a7dc in H5FL_blk_calloc (head=0x2, size=1984) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FL.c:819
#10 H5FL_seq_calloc (head=0x2, elem=elem@entry=62) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FL.c:1651
#11 0x0000000000622ba3 in H5FS__sinfo_new (f=f@entry=0xa86e470, fspace=fspace@entry=0xa8b7800) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FSsection.c:142
#12 0x0000000000624504 in H5FS__sinfo_lock (f=0xa86e470, fspace=0xa8b7800, accmode=0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FSsection.c:272
#13 H5FS_sect_add (f=f@entry=0xa86e470, fspace=fspace@entry=0xa8b7800, sect=sect@entry=0xa8ad000, flags=flags@entry=2, op_data=op_data@entry=0x7fffffffd5e8,
    merged_or_shrunk=merged_or_shrunk@entry=0x7fffffffd647) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5FSsection.c:1326
#14 0x00000000006b4365 in H5MF__add_sect (f=0xa86e470, alloc_type=H5FD_MEM_DRAW, fspace=0xa8b7800, node=0xa8ad000, merged_or_shrunk=0x7fffffffd647)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MF.c:635
#15 H5MF_xfree (f=f@entry=0xa86e470, alloc_type=alloc_type@entry=H5FD_MEM_DRAW, addr=addr@entry=2243, size=size@entry=2008)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MF.c:1180
#16 0x00000000006c03cc in H5MF__aggr_reset (f=0xa86e470, aggr=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MFaggr.c:725
#17 H5MF_free_aggrs (f=f@entry=0xa86e470) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MFaggr.c:791
#18 0x00000000005a5173 in H5F__flush_phase1 (f=0x2) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2314
#19 H5F__dest (f=0x2, f@entry=0xa86e470, flush=248, free_on_failure=244) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:1424
#20 0x00000000005a759f in H5F_try_close (f=f@entry=0xa86e470, was_closed=was_closed@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2685
#21 0x00000000005a6c0b in H5F__close (f=f@entry=0xa86e470) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2487
#22 0x0000000000a4a5f0 in H5VL__native_file_close (file=file@entry=0xa86e470, dxpl_id=<optimized out>, req=<optimized out>)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLnative_file.c:777
#23 0x0000000000a1cfc5 in H5VL__file_close (obj=0xa86e470, cls=0xa869d70, dxpl_id=140737488343008, req=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:4326
#24 H5VL_file_close (vol_obj=vol_obj@entry=0xa872f20, dxpl_id=140737488343008, req=req@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:4360
#25 0x00000000005ac330 in H5F__close_cb (file_vol_obj=file_vol_obj@entry=0xa872f20, request=request@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:249
#26 0x000000000069af84 in H5I__dec_ref (id=72057594037927937, request=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1076
#27 H5I__dec_app_ref (id=72057594037927937, request=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1156
#28 H5I_dec_app_ref (id=id@entry=72057594037927937) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1201
#29 0x0000000000591a46 in H5Fclose (file_id=file_id@entry=72057594037927937) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5F.c:1040
#30 0x00000000004361d8 in copy_objects (
    fnamein=fnamein@entry=0x7fffffffe50e "/tmp/cbh_tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.19cfba42a6.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    fnameout=fnameout@entry=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:390
#31 0x000000000045d111 in h5repack (infile=0x7fffffffe50e "/tmp/cbh_tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.19cfba42a6.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    outfile=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack.c:53
#32 0x0000000000463ade in main (argc=<optimized out>, argv=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_main.c:1037
(gdb)

### LINKED ISSUE #6126: h5repack aborts with heap corruption when using -S NONE
**Describe the bug**
Running h5repack with -S NONE on a crafted HDF5 input file causes the tool to abort due to heap corruption, detected by the GNU C Library allocator.

**Steps to Reproduce:**
The PoC attachment contains the input file that triggers the crash:

[PoC.zip](https://github.com/user-attachments/files/24281707/PoC.zip)

COMMAND LINE: ./h5repack -S NONE Heap_Corruption_2 out.h5

**Expected behavior**
h5repack should handle malformed input gracefully and either reject the file or exit cleanly with an error message, rather than aborting due to heap corruption.

**Platform (please complete the following information)**
 - HDF5 version:
   Git develop branch
    commit: 441d83a8962ef3571f0969bf923186e2ac4dc8c4
 - OS and version:
   Ubuntu 18.04.6 LTS
 - Compiler and version:
   clang 14.0.6 (used via hfuzz-clang wrapper)
 - Build system (e.g. CMake version) and generator (e.g. XCode, Ninja):
   Build system: CMake 3.30.0
   Generator: default Unix Makefiles (via cmake -S . -B build)
 - Any configure options you specified:
   -DHDF5_BUILD_TOOLS=ON -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_TESTING=OFF -
    DHDF5_BUILD_HL_LIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -
    DCMAKE_BUILD_TYPE=RelWithDebInfo, compiler flags include -g -O2 -fsanitize-coverage=trace-pc-guard -
    finstrument-functions.
 - MPI library and version (parallel HDF5):
   Parallel HDF5 not enabled; no MPI library used.

**Additional context**
GDB output excerpt:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
malloc_consolidate(): invalid chunk size

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6e367f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6e7f837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6faca7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e868ba in malloc_printerr (str=str@entry=0x7ffff6fae2d8 "malloc_consolidate(): invalid chunk size") at malloc.c:5342
#4  0x00007ffff6e86b5e in malloc_consolidate (av=av@entry=0x7ffff71e1c40 <main_arena>) at malloc.c:4471
#5  0x00007ffff6e8a848 in _int_malloc (av=av@entry=0x7ffff71e1c40 <main_arena>, bytes=bytes@entry=2096) at malloc.c:3713
#6  0x00007ffff6e8d0ac in __GI___libc_malloc (bytes=2096) at malloc.c:3067
#7  0x00000000004e8d9f in H5C__flush_single_entry (f=f@entry=0xa86e470, entry_ptr=entry_ptr@entry=0xa877570, flags=flags@entry=16384)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Centry.c:540
#8  0x000000000050422a in H5C__flush_ring (f=0x2, f@entry=0xa86e470, ring=ring@entry=1, flags=flags@entry=0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Cint.c:1748
#9  0x00000000004e4531 in H5C_flush_cache (f=f@entry=0xa86e470, flags=flags@entry=0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5C.c:710
#10 0x00000000004bbfb8 in H5AC_flush (f=f@entry=0xa86e470) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5AC.c:645
#11 0x00000000005a6742 in H5F__flush_phase2 (f=f@entry=0xa86e470, closing=true) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2346
#12 0x00000000005a52e2 in H5F__dest (f=f@entry=0xa86e470, flush=24, free_on_failure=20) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:1441
#13 0x00000000005a759f in H5F_try_close (f=f@entry=0xa86e470, was_closed=was_closed@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2685
#14 0x00000000005a6c0b in H5F__close (f=f@entry=0xa86e470) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:2487
#15 0x0000000000a4a5f0 in H5VL__native_file_close (file=file@entry=0xa86e470, dxpl_id=<optimized out>, req=<optimized out>)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLnative_file.c:777
#16 0x0000000000a1cfc5 in H5VL__file_close (obj=0xa86e470, cls=0xa869d70, dxpl_id=140737488343168, req=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:4326
#17 H5VL_file_close (vol_obj=vol_obj@entry=0xa8731b0, dxpl_id=140737488343168, req=req@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:4360
#18 0x00000000005ac330 in H5F__close_cb (file_vol_obj=file_vol_obj@entry=0xa8731b0, request=request@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Fint.c:249
#19 0x000000000069af84 in H5I__dec_ref (id=72057594037927937, request=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1076
#20 H5I__dec_app_ref (id=72057594037927937, request=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1156
#21 H5I_dec_app_ref (id=id@entry=72057594037927937) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Iint.c:1201
#22 0x0000000000591a46 in H5Fclose (file_id=file_id@entry=72057594037927937) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5F.c:1040
#23 0x00000000004361d8 in copy_objects (
    fnamein=fnamein@entry=0x7fffffffe510 "/tmp/cbh_tmp/559_S_NONE/SIGABRT.PC.7ffff6e34e87.STACK.19cfba42a6.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    fnameout=fnameout@entry=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:390
#24 0x000000000045d111 in h5repack (infile=0x7fffffffe510 "/tmp/cbh_tmp/559_S_NONE/SIGABRT.PC.7ffff6e34e87.STACK.19cfba42a6.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    outfile=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack.c:53
#25 0x0000000000463ade in main (argc=<optimized out>, argv=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_main.c:1037
(gdb)

### LINKED ISSUE #6133: h5repack aborts with double free during object copy on malformed HDF5 input
**Describe the bug**
Running h5repack on a crafted HDF5 file causes the tool to abort with SIGABRT due to a double free detected by the GNU C Library allocator during object copy processing.

**Steps to Reproduce:**
The PoC attachment contains the input file that triggers the crash:

[PoC.zip](https://github.com/user-attachments/files/24361694/PoC.zip)

COMMAND LINE: ./h5repack --low 2 -v 2 Double_Free_3 out.h5

**Expected behavior**
h5repack should detect the malformed input and exit cleanly with an error message, rather than aborting with a double free and SIGABRT.

**Platform (please complete the following information)**
HDF5 version:
Git develop branch
commit: 441d83a8962ef3571f0969bf923186e2ac4dc8c4
OS and version:
Ubuntu 18.04.6 LTS
Compiler and version:
clang 14.0.6 (used via hfuzz-clang wrapper)
Build system (e.g. CMake version) and generator (e.g. XCode, Ninja):
Build system: CMake 3.30.0
Generator: default Unix Makefiles (via cmake -S . -B build)
Any configure options you specified:
-DHDF5_BUILD_TOOLS=ON -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_TESTING=OFF -
DHDF5_BUILD_HL_LIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -
DCMAKE_BUILD_TYPE=RelWithDebInfo, compiler flags include -g -O2 -fsanitize-coverage=trace-pc-guard -
finstrument-functions.
MPI library and version (parallel HDF5):
Parallel HDF5 not enabled; no MPI library used.

**Additional context**
GDB output excerpt:
 group                                                    /
free(): double free detected in tcache 2

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6e367f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6e7f837 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6faca7b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e868ba in malloc_printerr (str=str@entry=0x7ffff6fae6e8 "free(): double free detected in tcache 2") at malloc.c:5342
#4  0x00007ffff6e8e0ed in _int_free (have_lock=0, p=0xa873e00, av=0x7ffff71e1c40 <main_arena>) at malloc.c:4195
#5  __GI___libc_free (mem=0xa873e10) at malloc.c:3134
#6  0x00000000006c3057 in H5MM_xfree (mem=mem@entry=0xa873e10) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5MM.c:201
#7  0x0000000000adb241 in H5D__chunk_copy (f_src=f_src@entry=0xa86c320, layout_src=layout_src@entry=0xa876e20, f_dst=f_dst@entry=0xa86e470, layout_dst=layout_dst@entry=0xa8891f0,
    ds_extent_src=<optimized out>, dt_src=0xa832990, pline_src=0x0, cpy_info=0x7fffffffd328) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Dchunk.c:7268
#8  0x000000000070a137 in H5O__layout_copy_file (file_src=0x2, file_src@entry=0xa86c320, mesg_src=mesg_src@entry=0xa876e20, file_dst=0x0, file_dst@entry=0xa86e470,
    recompute_size=recompute_size@entry=0x7fffffffd2cf, mesg_flags=mesg_flags@entry=0x7fffffffd278, cpy_info=0x7fffffffd328, _udata=0xa875b20)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Olayout.c:1083
#9  0x00000000007158b1 in H5O__msg_copy_file (type=type@entry=0xe12d00 <H5O_MSG_LAYOUT>, file_src=0xa86c320, native_src=0x7fffffffc7a0, native_src@entry=0xa876e20, file_dst=0x0,
    recompute_size=0x7ffff6e34e87 <__GI_raise+199>, recompute_size@entry=0x7fffffffd2cf, mesg_flags=mesg_flags@entry=0x7fffffffd278, cpy_info=0x7fffffffd328, udata=0xa875b20)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Omessage.c:1687
#10 0x00000000006e0e68 in H5O__copy_header_real (oloc_src=<optimized out>, oloc_src@entry=0x7fffffffd428, oloc_dst=0x0, oloc_dst@entry=0x7fffffffd410,
    cpy_info=cpy_info@entry=0x7fffffffd328, obj_type=obj_type@entry=0x0, udata=udata@entry=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Ocopy.c:469
#11 0x00000000006e3f2e in H5O__copy_header (oloc_src=0x2, oloc_dst=0x7fffffffc7a0, oloc_dst@entry=0x7fffffffd410, ocpypl_id=ocpypl_id@entry=792633534417207326,
    lcpl_id=lcpl_id@entry=792633534417207312) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Ocopy.c:1006
#12 0x00000000006df337 in H5O__copy_obj (src_loc=0x7fffffffd460, dst_loc=0x7fffffffd4d0, dst_name=0xa873190 "/DS1", ocpypl_id=0, lcpl_id=792633534417207312)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Ocopy.c:1057
#13 H5O__copy (loc=loc@entry=0x7fffffffd4c0, src_name=src_name@entry=0xa873190 "/DS1", dst_loc=dst_loc@entry=0x7fffffffd4d0, dst_name=dst_name@entry=0xa873190 "/DS1",
    ocpypl_id=0, lcpl_id=792633534417207312) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5Ocopy.c:162
#14 0x0000000000a4d6ff in H5VL__native_object_copy (src_obj=src_obj@entry=0xa86c320, loc_params1=loc_params1@entry=0x7fffffffd5f8, src_name=0x7fffffffc7a0 "",
    src_name@entry=0xa873190 "/DS1", dst_obj=dst_obj@entry=0xa86e470, loc_params2=loc_params2@entry=0x7fffffffd620, dst_name=0x7ffff6e34e87 <__GI_raise+199> "H\213\214$\b\001",
    dst_name@entry=0xa873190 "/DS1", ocpypl_id=792633534417207326, lcpl_id=792633534417207312, dxpl_id=<optimized out>, req=<optimized out>)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLnative_object.c:154
#15 0x0000000000a26a36 in H5VL__object_copy (src_obj=0x2, src_loc_params=0x7fffffffc7a0, src_name=0x0, dst_obj=0xa86e470, dst_loc_params=0x0, dst_name=0x7fffffffc7a0 "",
    cls=0xa869d70, dxpl_id=792633534417207304, req=0x0, ocpypl_id=<optimized out>, lcpl_id=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:5937
#16 H5VL_object_copy (src_obj=<optimized out>, src_loc_params=0x7fffffffc7a0, src_loc_params@entry=0x7fffffffd5f8, src_name=0x0, src_name@entry=0xa873190 "/DS1",
    dst_obj=<optimized out>, dst_loc_params=0x0, dst_loc_params@entry=0x7fffffffd620, dst_name=0x7fffffffc7a0 "", dst_name@entry=0xa873190 "/DS1", ocpypl_id=792633534417207326,
    lcpl_id=792633534417207312, dxpl_id=792633534417207304, req=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5VLcallback.c:5979
#17 0x00000000006c54d9 in H5O__copy_api_common (src_loc_id=src_loc_id@entry=72057594037927936, src_name=0x0, src_name@entry=0xa873190 "/DS1",
    dst_loc_id=dst_loc_id@entry=72057594037927937, dst_name=dst_name@entry=0xa873190 "/DS1", ocpypl_id=ocpypl_id@entry=792633534417207326, lcpl_id=792633534417207312,
    lcpl_id@entry=0, token_ptr=0x0, _vol_obj_ptr=0x0) at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5O.c:445
#18 0x00000000006c4fc5 in H5Ocopy (src_loc_id=src_loc_id@entry=72057594037927936, src_name=0x7fffffffc7a0 "", dst_loc_id=0, dst_loc_id@entry=72057594037927937,
    dst_name=0x7ffff6e34e87 <__GI_raise+199> "H\213\214$\b\001", ocpypl_id=0, ocpypl_id@entry=792633534417207326, lcpl_id=140737488340896, lcpl_id@entry=0)
    at /root/DriveSched/benchmarks/hdf5/hdf5/src/H5O.c:536
#19 0x000000000043a34e in do_copy_objects (fidin=2, fidin@entry=72057594037927936, fidout=0, fidout@entry=72057594037927937, travt=0xa872e50, options=options@entry=0xa809360)
    at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:1294
#20 0x0000000000437abf in copy_objects (
    fnamein=fnamein@entry=0x7fffffffe50e "/tmp/cbh_tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.1921fe138a.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    fnameout=fnameout@entry=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_copy.c:326
#21 0x000000000045d111 in h5repack (infile=0x7fffffffe50e "/tmp/cbh_tmp/73_low_2_v_2/SIGABRT.PC.7ffff6e34e87.STACK.1921fe138a.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rcx.fuzz",
    outfile=0x7fffffffe583 "out.h5", options=options@entry=0xa809360) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack.c:53
#22 0x0000000000463ade in main (argc=<optimized out>, argv=<optimized out>) at /root/DriveSched/benchmarks/hdf5/hdf5/tools/src/h5repack/h5repack_main.c:1037

### PR DESCRIPTION
**Pull request by jhendersonHDF**
Fix double-free caused by loss of buffer pointer after re-allocation

----

> [!IMPORTANT]
> Fix double-free bug in `H5D__chunk_copy()` by updating buffer pointers after reallocation and initializing `udata`.
> 
>   - **Bug Fix**:
>     - Fix double-free bug in `H5D__chunk_copy()` in `H5Dchunk.c` by ensuring buffer pointers are updated after reallocation.
>     - Initialize `H5D_chunk_it_ud3_t udata` with `{0}` to prevent uninitialized memory usage.
>   - **Documentation**:
>     - Update `CHANGELOG.md` to document the fix for the double-free bug and reference related GitHub issues.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=HDFGroup%2Fhdf5&utm_source=github&utm_medium=referral)<sup> for e60ef3e57fee336cb9529fbabdd33a6213fd9607. You can [customize](https://app.ellipsis.dev/HDFGroup/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by brtnfld — DISMISSED** [review]

File: src/H5Dchunk.c [hunk 1]
```diff
@@ -7202,7 +7202,6 @@ H5D__chunk_copy(H5F_t *f_src, H5O_layout_t *layout_src, H5F_t *f_dst, H5O_layout
         HGOTO_ERROR(H5E_RESOURCE, H5E_NOSPACE, FAIL, "memory allocation failed for raw data chunk");
 
     /* Initialize the callback structure for the source */
-    memset(&udata, 0, sizeof udata);
```
Comment (bmribler) [inline src/H5Dchunk.c:7260]: I like this initialization-at-declaration approach compared to the usual memset. Is this intended as a local fix, or a direction we’re moving toward more generally?

**Review by bmribler — DISMISSED** [review]

File: src/H5Dchunk.c (hunk 1 above)
Comment (jhendersonHDF) [reply src/H5Dchunk.c:7260]: After the changes in this PR, it's necessary to ensure that the buffers are NULL in case the `done:` section is skipped to before this `memset` call would have been made. Using a struct initializer is generally my preferred way though for cases where it makes sense.

File: src/H5Dchunk.c [hunk 2]
```diff
@@ -7202,7 +7202,6 @@ H5D__chunk_copy(H5F_t *f_src, H5O_layout_t *layout_src, H5F_t *f_dst, H5O_layout
         HGOTO_ERROR(H5E_RESOURCE, H5E_NOSPACE, FAIL, "memory allocation failed for raw data chunk");
 
     /* Initialize the callback structure for the source */
```
Comment (fortnern) [inline src/H5Dchunk.c:7259]: It might be a good idea to move the lines that set buf and buf_size in udata to be immediately after the malloc:

```
/* Allocate memory for copying the chunk and save it in udata */
if (NULL == (buf = H5MM_malloc(buf_size)))
    HGOTO_ERROR(H5E_RESOURCE, H5E_NOSPACE, FAIL, "memory allocation failed for raw data chunk");
udata.buf              = buf;
udata.buf_size = buf_size;
```

To make it clear nothing can come between them that might issue an error. Actually it might be preferable to get rid of buf entirely and just use udata.buf.

Also, do we need to handle bkg similarly?

Comment (jhendersonHDF) [reply src/H5Dchunk.c:7259]: > Actually it might be preferable to get rid of buf entirely and just use udata.buf.
> Also, do we need to handle bkg similarly?

It doesn't seem like `buf` or `bkg` serve any particular purpose in this function currently, so I'd be fine with this as well. `bkg` does need to be handled similarly if this is done.

Comment (fortnern) [reply src/H5Dchunk.c:7259]: I think we should go ahead and do this, it simplifies the code and reduces the problem of needing to track who owns the buffers since each is only stored in one place.

**Review by brtnfld — APPROVED** [review]

**Review by bmribler — APPROVED** [review]
