### PR TITLE
Fix out of bounds in `hdf5/src/H5Fint.c:2859`

### LINKED ISSUE #2432: [BUG] Out of bounds access on read in hdf5/src/H5Fint.c:2859:13
Hi! We have been fuzzing your project with [sydr-fuzz](https://github.com/kobrineli/oss-sydr-fuzz)
and found out of bounds access on read in `hdf5/src/H5Fint.c:2859:13`.

### Environment

- OS: ubuntu 20.04
- hdf5 version: 509fe962d42b3f02d356d2668b04712df06daf7f

### How to reprocude the error

1. Build docker container from [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/hdf5)

        sudo docker build -t oss-sydr-fuzz-hdf5 .

2. Run docker container

        sudo docker run --rm -v `pwd`:/fuzz -it oss-sydr-fuzz-hdf5 /bin/bash

3. Run `/h5_read_afl` with [input](https://github.com/HDFGroup/hdf5/files/10673827/crash-244484e1ab5cd0acab3563fa35bf2981c7d41c92.txt)

        /h5_read_afl crash-244484e1ab5cd0acab3563fa35bf2981c7d41c92.txt

4. You will see the following output

        ==14==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d000005af8 at pc 0x0000008b8207 bp 0x7ffce6f47b30 sp 0x7ffce6f47b28
        READ of size 1 at 0x60d000005af8 thread T0
            #0 0x8b8206 in H5F_addr_decode_len /hdf5/src/H5Fint.c:2859:13
            #1 0x9a4f44 in H5G_ent_decode /hdf5/src/H5Gent.c:148:13
            #2 0x8fb744 in H5F__cache_superblock_deserialize /hdf5/src/H5Fsuper_cache.c:521:13
            #3 0x622ea4 in H5C__load_entry /hdf5/src/H5C.c:7298:26
            #4 0x622ea4 in H5C_protect /hdf5/src/H5C.c:2330:30
            #5 0x53bde1 in H5AC_protect /hdf5/src/H5AC.c:1394:26
            #6 0x8debd4 in H5F__super_read /hdf5/src/H5Fsuper.c:449:42
            #7 0x89f14a in H5F_open /hdf5/src/H5Fint.c:1964:13
            #8 0x146ddd4 in H5VL__native_file_open /hdf5/src/H5VLnative_file.c:127:29
            #9 0x14222a6 in H5VL__file_open /hdf5/src/H5VLcallback.c:3674:30
            #10 0x14218e5 in H5VL_file_open /hdf5/src/H5VLcallback.c:3823:30
            #11 0x876c29 in H5F__open_api_common /hdf5/src/H5F.c:794:29
            #12 0x8762ef in H5Fopen /hdf5/src/H5F.c:835:22
            #13 0x50c113 in LLVMFuzzerTestOneInput /h5_read_fuzzer.c:35:7
            #14 0x43b301 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
            #15 0x42521c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
            #16 0x42af6b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
            #17 0x454502 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
            #18 0x7f682830f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
            #19 0x41fb3d in _start (/h5_read_fuzzer+0x41fb3d)
        
        0x60d000005af8 is located 0 bytes to the right of 136-byte region [0x60d000005a70,0x60d000005af8)
        allocated by thread T0 here:
            #0 0x4d5629 in __interceptor_realloc /llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:148:3
            #1 0xba2b83 in H5MM_realloc /hdf5/src/H5MM.c:144:21
            #2 0x622856 in H5C__load_entry /hdf5/src/H5C.c:7213:46
            #3 0x622856 in H5C_protect /hdf5/src/H5C.c:2330:30
            #4 0x53bde1 in H5AC_protect /hdf5/src/H5AC.c:1394:26
            #5 0x8debd4 in H5F__super_read /hdf5/src/H5Fsuper.c:449:42
            #6 0x89f14a in H5F_open /hdf5/src/H5Fint.c:1964:13
            #7 0x146ddd4 in H5VL__native_file_open /hdf5/src/H5VLnative_file.c:127:29
            #8 0x14222a6 in H5VL__file_open /hdf5/src/H5VLcallback.c:3674:30
            #9 0x14218e5 in H5VL_file_open /hdf5/src/H5VLcallback.c:3823:30
            #10 0x876c29 in H5F__open_api_common /hdf5/src/H5F.c:794:29
            #11 0x8762ef in H5Fopen /hdf5/src/H5F.c:835:22
            #12 0x50c113 in LLVMFuzzerTestOneInput /h5_read_fuzzer.c:35:7
            #13 0x43b301 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
            #14 0x42521c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
            #15 0x42af6b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
            #16 0x454502 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
            #17 0x7f682830f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
        
        SUMMARY: AddressSanitizer: heap-buffer-overflow /hdf5/src/H5Fint.c:2859:13 in H5F_addr_decode_len
        Shadow bytes around the buggy address:
          0x0c1a7fff8b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c1a7fff8b10: 00 fa fa fa fa fa fa fa fa fa 00 00 00 00 00 00
          0x0c1a7fff8b20: 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa fa
          0x0c1a7fff8b30: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
          0x0c1a7fff8b40: 00 00 00 00 00 fa fa fa fa fa fa fa fa fa 00 00
        =>0x0c1a7fff8b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00[fa]
          0x0c1a7fff8b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c1a7fff8b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c1a7fff8b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c1a7fff8b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
          0x0c1a7fff8ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
        Shadow byte legend (one shadow byte represents 8 application bytes):
          Addressable:           00
          Partially addressable: 01 02 03 04 05 06 07 
          Heap left redzone:       fa
          Freed heap region:       fd
          Stack left redzone:      f1
          Stack mid redzone:       f2
          Stack right redzone:     f3
          Stack after return:      f5
          Stack use after scope:   f8
          Global redzone:          f9
          Global init order:       f6
          Poisoned by user:        f7
          Container overflow:      fc
          Array cookie:            ac
          Intra object redzone:    bb
          ASan internal:           fe
          Left alloca redzone:     ca
          Right alloca redzone:    cb
        ==14==ABORTING

### PR DESCRIPTION
**Pull request by kobrineli**
Hi! Some time ago I reported an out of bounds error in `hdf5/src/H5Fint.c:2859` #2432.
I fixed the error by myself by adding some checks on `image` pointer. I've tested the fixed version on the input that led to error, now it works fine.

Closes #2432

### CODE REVIEW

File: src/H5Fsuper_cache.c [hunk 1]
```diff
@@ -444,13 +446,21 @@ H5F__cache_superblock_deserialize(const void *_image, size_t H5_ATTR_NDEBUG_UNUS
         if (HDF5_FREESPACE_VERSION != *image++)
             HGOTO_ERROR(H5E_FILE, H5E_BADVALUE, NULL, "bad free space version number")
 
+        /* Check whether the image pointer is out of bounds */
+        if (image >= image_end)
```
Comment (mattjala) [inline src/H5Fsuper_cache.c]: Should be done before previous check that uses `image`

File: src/H5Fsuper_cache.c [hunk 2]
```diff
@@ -444,13 +446,21 @@ H5F__cache_superblock_deserialize(const void *_image, size_t H5_ATTR_NDEBUG_UNUS
...
+	    HGOTO_ERROR(H5E_FILE, H5E_BADRANGE, NULL, "image pointer is out of bounds")
```
Comment (mattjala) [inline src/H5Fsuper_cache.c]: `H5E_OVERFLOW` would be a more appropriate minor error code, and consistent with buffer checks in other functions

File: src/H5Fsuper_cache.c [hunk 3]
```diff
@@ -498,13 +512,22 @@ H5F__cache_superblock_deserialize(const void *_image, size_t H5_ATTR_NDEBUG_UNUS
...
+		if (image >= image_end)
+		    HGOTO_ERROR(H5E_FILE, H5E_BADRANGE, NULL, "image pointer is out of bounds")
+	    }
+	}                   /* end if */
         else
             chunk_btree_k = HDF5_BTREE_CHUNK_IK_DEF;
         udata->btree_k[H5B_CHUNK_ID] = chunk_btree_k;
 
+	/* Check whether the image pointer will be out of bounds */
+	if (image + H5F_SIZEOF_ADDR(udata->f) * 4 >= image_end)
```
Comment (mattjala) [inline src/H5Fsuper_cache.c]: Is there a reason this check looks ahead 4 times size of address when only 2 addresses are decoded? Same question for line 584.

File: src/H5Fsuper_cache.c [hunk 4]
```diff
@@ -466,6 +476,10 @@ H5F__cache_superblock_deserialize(const void *_image, size_t H5_ATTR_NDEBUG_UNUS
         /* Skip over reserved byte */
         image++;
 
+        /* Check whether the image pointer is out of bounds */
+        if (image + 2 >= image_end)
```
Comment (mattjala) [inline src/H5Fsuper_cache.c]: `sizeof(uint16_t)` would be more understandable than hardcoded `2`

File: src/H5Gent.c [hunk 5]
```diff
@@ -144,11 +156,15 @@ H5G_ent_decode(const H5F_t *f, const uint8_t **pp, H5G_entry_t *ent)
...
         case H5G_CACHED_STAB:
             HDassert(2 * H5F_SIZEOF_ADDR(f) <= H5G_SIZEOF_SCRATCH);
+	    if (*pp + H5F_SIZEOF_ADDR(f) * 2 >= p_end)
+		HGOTO_ERROR(H5E_FILE, H5E_BADRANGE, NULL, "image pointer is out of bounds")
             H5F_addr_decode(f, pp, &(ent->cache.stab.btree_addr));
             H5F_addr_decode(f, pp, &(ent->cache.stab.heap_addr));
             break;
 
         case H5G_CACHED_SLINK:
+	    if (*pp + 4 >= p_end)
```
Comment (mattjala) [inline src/H5Gent.c]: `sizeof(uint32_t)` would be more understandable than hardcoded `4`

File: src/H5Fsuper_cache.c (hunk 3 above)
Comment (kobrineli) [reply src/H5Fsuper_cache.c]: Github diff shortened the following code, there are 2 more address decodes after these two.

File: src/H5Fsuper_cache.c (hunk 1 above)
Comment (kobrineli) [reply src/H5Fsuper_cache.c]: fixed

File: src/H5Fsuper_cache.c (hunk 2 above)
Comment (kobrineli) [reply src/H5Fsuper_cache.c]: fixed

File: src/H5Fsuper_cache.c (hunk 4 above)
Comment (kobrineli) [reply src/H5Fsuper_cache.c]: fixed

File: src/H5Gent.c (hunk 5 above)
Comment (kobrineli) [reply src/H5Gent.c]: fixed

**Comment by kobrineli** [comment]
@mattjala, I've fixed

**Review by mattjala — APPROVED** [review]

**Comment by jhendersonHDF** [comment]
Hi @kobrineli, apologies for the extra burden, but would it be possible to merge in the latest changes from the HDF5 "develop" branch and refactor this PR to be in the style of the other buffer checks we've been adding recently? See https://github.com/HDFGroup/hdf5/pull/2679 for example where the "buffer end" variable is set to `buffer_pointer + len - 1` and then we use a new H5_IS_BUFFER_OVERFLOW macro that takes the buffer pointer, the size of the thing being checked and the buffer end pointer. This way your new checks will be consistent with all the other places that use the new macro.

**Comment by kobrineli** [comment]
@jhendersonHDF 

Okay, I'll do it as soon as possible.

**Comment by jhendersonHDF** [comment]
@kobrineli Thanks! Just to move the process of getting this merged along, you should also add a small entry in release_docs/RELEASE.txt under the "bugs fixed" section describing your fix and any associated CVEs. You should see some examples of recent entries for CVE fixes there that you can use; the entries are organized by date.

**Comment by kobrineli** [comment]
@jhendersonHDF 
I didn't registered any CVE for the issue which will be closed by this PR. 
Is it possible to register it and how?

**Comment by jhendersonHDF** [comment]
@kobrineli If there aren't any CVE issues associated with the fix, then just list any GitHub issue number associated with the fix, if any. The typical format for RELEASE.txt entries is:

- Short description

  Long description

  (Initials - Date, GitHub issue number/CVE number/etc.)

**Comment by kobrineli** [comment]
@jhendersonHDF 
Got it, thanks a lot

**Comment by kobrineli** [comment]
@jhendersonHDF 

Hi! I've changed buffer overflow checks to the new macro and updated the RELEASE.txt with the issue description.

File: src/H5Fsuper_cache.c [hunk 6]
```diff
@@ -433,24 +433,38 @@ H5F__cache_superblock_deserialize(const void *_image, size_t H5_ATTR_NDEBUG_UNUS
     if (H5F__superblock_prefix_decode(sblock, &image, udata, FALSE) < 0)
         HGOTO_ERROR(H5E_FILE, H5E_CANTDECODE, NULL, "can't decode file superblock prefix")
 
+    const uint8_t *image_end = _image + len - 1;
```
Comment (jhendersonHDF) [inline src/H5Fsuper_cache.c]: Looks like the -Werror builds are failing due to arithmetic on a void pointer here. Suggest changing `_image` to `image`. Also, the clang format check was a little grumpy.

**Comment by jhendersonHDF** [comment]
> @jhendersonHDF
> 
> Hi! I've changed buffer overflow checks to the new macro and updated the RELEASE.txt with the issue description.

Thanks for the updates! This PR looks close; just a couple minor cleanup things to take care of.

**Review by qkoziol — APPROVED** [review]

File: src/H5Fsuper_cache.c (hunk 6 above)
Comment (jhendersonHDF) [reply src/H5Fsuper_cache.c]: Codespell's also complaining about the RELEASE.txt entry

Comment (kobrineli) [reply src/H5Fsuper_cache.c]: Fixed

File: src/H5Gent.c [hunk 7]
```diff
@@ -130,11 +130,22 @@ H5G_ent_decode(const H5F_t *f, const uint8_t **pp, H5G_entry_t *ent)
     HDassert(pp);
     HDassert(ent);
 
+    if (H5_IS_BUFFER_OVERFLOW(*pp, ent->name_off, p_end))
+        HGOTO_ERROR(H5E_FILE, H5E_OVERFLOW, NULL, "image pointer is out of bounds")
```
Comment (jhendersonHDF) [inline src/H5Gent.c]: Ah I didn't catch this the first time but all the error values returned in this function should be updated to FAIL rather than NULL since H5G_ent_decode returns an herr_t

Comment (kobrineli) [reply src/H5Gent.c]: oh, ok

I'll fix this soon

Comment (kobrineli) [reply src/H5Gent.c]: fixed

**Comment by kobrineli** [comment]
@jhendersonHDF 

Something fails in the tests that is not related to changes in this PR

**Comment by jhendersonHDF** [comment]
> @jhendersonHDF
> 
> Something fails in the tests that is not related to changes in this PR

Looks like those are mostly cascading failures from earlier on, but still related to the changes here. For example:

```
2023-04-13T19:59:08.0177358Z   #000: /home/runner/work/hdf5/hdf5/src/H5G.c line 598 in H5Gget_info(): unable to synchronously get group info
2023-04-13T19:59:08.0177733Z     major: Symbol table
2023-04-13T19:59:08.0178072Z     minor: Can't get value
2023-04-13T19:59:08.0178477Z   #001: /home/runner/work/hdf5/hdf5/src/H5G.c line 573 in H5G__get_info_api_common(): unable to get group info
2023-04-13T19:59:08.0178851Z     major: Symbol table
2023-04-13T19:59:08.0179159Z     minor: Can't get value
2023-04-13T19:59:08.0179720Z   #002: /home/runner/work/hdf5/hdf5/src/H5VLcallback.c line 4643 in H5VL_group_get(): group get failed
2023-04-13T19:59:08.0180107Z     major: Virtual Object Layer
2023-04-13T19:59:08.0180441Z     minor: Can't get value
2023-04-13T19:59:08.0180821Z   #003: /home/runner/work/hdf5/hdf5/src/H5VLcallback.c line 4612 in H5VL__group_get(): group get failed
2023-04-13T19:59:08.0181202Z     major: Virtual Object Layer
2023-04-13T19:59:08.0181527Z     minor: Can't get value
2023-04-13T19:59:08.0182050Z   #004: /home/runner/work/hdf5/hdf5/src/H5VLnative_group.c line 201 in H5VL__native_group_get(): can't retrieve group info
2023-04-13T19:59:08.0182439Z     major: Symbol table
2023-04-13T19:59:08.0182759Z     minor: Can't get value
2023-04-13T19:59:08.0183219Z   #005: /home/runner/work/hdf5/hdf5/src/H5Gobj.c line 741 in H5G__obj_info(): can't count objects
2023-04-13T19:59:08.0183562Z     major: Symbol table
2023-04-13T19:59:08.0183887Z     minor: Can't count elements
2023-04-13T19:59:08.0184284Z   #006: /home/runner/work/hdf5/hdf5/src/H5Gstab.c line 611 in H5G__stab_count(): iteration operator failed
2023-04-13T19:59:08.0184660Z     major: Symbol table
2023-04-13T19:59:08.0184951Z     minor: Unable to initialize object
2023-04-13T19:59:08.0185439Z   #007: /home/runner/work/hdf5/hdf5/src/H5B.c line 1194 in H5B_iterate(): B-tree iteration failed
2023-04-13T19:59:08.0185835Z     major: B-Tree node
2023-04-13T19:59:08.0186121Z     minor: Iteration failed
2023-04-13T19:59:08.0186601Z   #008: /home/runner/work/hdf5/hdf5/src/H5B.c line 1153 in H5B__iterate_helper(): B-tree iteration failed
2023-04-13T19:59:08.0187002Z     major: B-Tree node
2023-04-13T19:59:08.0187291Z     minor: Iteration failed
2023-04-13T19:59:08.0187762Z   #009: /home/runner/work/hdf5/hdf5/src/H5B.c line 1153 in H5B__iterate_helper(): B-tree iteration failed
2023-04-13T19:59:08.0188157Z     major: B-Tree node
2023-04-13T19:59:08.0188439Z     minor: Iteration failed
2023-04-13T19:59:08.0188844Z   #010: /home/runner/work/hdf5/hdf5/src/H5Gnode.c line 1021 in H5G__node_sumup(): unable to load symbol table node
2023-04-13T19:59:08.0189352Z     major: Symbol table
2023-04-13T19:59:08.0189667Z     minor: Unable to load metadata into cache
2023-04-13T19:59:08.0190069Z   #011: /home/runner/work/hdf5/hdf5/src/H5AC.c line 1350 in H5AC_protect(): H5C_protect() failed
2023-04-13T19:59:08.0190428Z     major: Object cache
2023-04-13T19:59:08.0190714Z     minor: Unable to protect metadata
2023-04-13T19:59:08.0191188Z   #012: /home/runner/work/hdf5/hdf5/src/H5C.c line 2147 in H5C_protect(): can't load entry
2023-04-13T19:59:08.0191540Z     major: Object cache
2023-04-13T19:59:08.0191850Z     minor: Unable to load metadata into cache
2023-04-13T19:59:08.0192334Z   #013: /home/runner/work/hdf5/hdf5/src/H5C.c line 6420 in H5C__load_entry(): Can't deserialize image
2023-04-13T19:59:08.0192695Z     major: Object cache
2023-04-13T19:59:08.0193006Z     minor: Unable to load metadata into cache
2023-04-13T19:59:08.0193439Z   #014: /home/runner/work/hdf5/hdf5/src/H5Gcache.c line 194 in H5G__cache_node_deserialize(): unable to decode symbol table entries
2023-04-13T19:59:08.0193846Z     major: Symbol table
2023-04-13T19:59:08.0194149Z     minor: Unable to load metadata into cache
2023-04-13T19:59:08.0194625Z   #015: /home/runner/work/hdf5/hdf5/src/H5Gent.c line 97 in H5G__ent_decode_vec(): can't decode
2023-04-13T19:59:08.0194964Z     major: Symbol table
2023-04-13T19:59:08.0195250Z     minor: Unable to decode value
2023-04-13T19:59:08.0196028Z   #016: /home/runner/work/hdf5/hdf5/src/H5Gent.c line 179 in H5G_ent_decode(): image pointer is out of bounds
2023-04-13T19:59:08.0196966Z     major: File accessibility
2023-04-13T19:59:08.0197187Z     minor: Address overflowed
```

File: src/H5Gent.c [hunk 8]
```diff
@@ -160,6 +175,9 @@ H5G_ent_decode(const H5F_t *f, const uint8_t **pp, H5G_entry_t *ent)
 
     *pp = p_ret + H5G_SIZEOF_ENTRY_FILE(f);
 
+    if (H5_IS_BUFFER_OVERFLOW(*pp, 1, p_end))
+        HGOTO_ERROR(H5E_FILE, H5E_OVERFLOW, FAIL, "image pointer is out of bounds")
```
Comment (jhendersonHDF) [inline src/H5Gent.c]: Looks like this check is triggering in a lot of places.

Comment (kobrineli) [reply src/H5Gent.c]: well, in fact, this check is after the last dereference, maybe it is not needed here

should I remove it?

File: src/H5Gent.c [hunk 9]
```diff
@@ -93,7 +93,7 @@ H5G__ent_decode_vec(const H5F_t *f, const uint8_t **pp, const uint8_t *p_end, H5
     for (u = 0; u < n; u++) {
         if (*pp > p_end)
             HGOTO_ERROR(H5E_SYM, H5E_CANTDECODE, FAIL, "ran off the end of the image buffer")
-        if (H5G_ent_decode(f, pp, ent + u) < 0)
+        if (H5G_ent_decode(f, pp, ent + u, p_end) < 0)
```
Comment (jhendersonHDF) [inline src/H5Gent.c:96]: From what I can tell the vast majority of the issues occur from this call to H5G_ent_decode, probably due to advancing the pointer past the end of the buffer on the last entry being decoded. It's probably fine to omit the last overrun check in H5G_ent_decode since the pointer isn't dereferenced past that point.

Comment (kobrineli) [reply src/H5Gent.c:96]: yes, I agree

pushed the changes with the removing of the last check

**Comment by jhendersonHDF** [comment]
@kobrineli Everything looks good now. Thanks for the work on fixing this and getting the PR in shape!

**Review by jhendersonHDF — APPROVED** [review]

**Comment by kobrineli** [comment]
@jhendersonHDF Thanks!
