### PR TITLE
Fix missing/misplaced h5_reset calls

### LINKED ISSUE #2990: `make check` failures w/ thread-safe + code stacks
**Describe the bug**
Encountered following errors:

H5VL_object_inc_rc function, FUNC_ENTER/LEAVE macro mismatch (FUNC_LEAVE_NOAPI should be FUNC_LEAVE_NOAPI_NOFS).

Two swmr test applications fail on H5FD__supports_swmr_test call, because HDF5 is not initialized. These are:
 - accum_swmr_reader.c
 - swmr.c

Inserting an H5open call before the "supports" call addresses that.

**Expected behavior**
All make checks tests should pass.

**Platform (please complete the following information)**
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.14.1-2
                  Configured on: Thu May 18 18:59:35 UTC 2023
                  Configured by: bappel@v4dev0
                    Host system: x86_64-pc-linux-gnu
              Uname information: Linux v4dev0 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /home/bappel/hdf5-1.14.1_debug

Compiling Options:
------------------
                     Build Mode: debug
              Debugging Symbols: yes
                        Asserts: yes
                      Profiling: yes
             Optimization Level: debug

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables:
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: -lpthread -lz -ldl -lm
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /usr/bin/gcc -std=gnu11 ( gcc (GCC) 4.8.5 20150623 )
                       CPPFLAGS: -g -m64
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -UNDEBUG -DH5AC_DEBUG -DH5B2_DEBUG -DH5CX_DEBUG -DH5D_DEBUG -DH5F_DEBUG -DH5HL_DEBUG -DH5I_DEBUG -DH5O_DEBUG -DH5S_DEBUG -DH5T_DEBUG -DH5Z_DEBUG -DH5_DEBUG_API -I/home/bappel/hdf5/src/H5FDsubfiling
                    AM_CPPFLAGS:
                        C Flags:
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wshadow -Wundef -Wwrite-strings -pedantic -Wno-c++-compat -Wvla -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized   -g -fno-omit-frame-pointer  -Wbad-function-cast -Wcast-align -Wformat -Wimplicit-function-declaration -Wint-to-pointer-cast -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-sign -Wpointer-to-int-cast -Wredundant-decls -Wstrict-prototypes -Wswitch -Wunused-but-set-variable -Wunused-variable -Wunused-function -Wunused-parameter -Waggregate-return -Wdisabled-optimization -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wswitch-default -Wswitch-enum -Wunsafe-loop-optimizations -Wunused-macros -Wjump-misses-init -Wstrict-overflow=5 -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wvector-operation-performance -Wsuggest-attribute=format -pg
                     AM C Flags:
               Shared C Library: yes
               Static C Library: yes

                        Fortran: no

                            C++: no

                           Java: no

Features:
---------
                     Parallel HDF5: no
  Parallel Filtered Dataset Writes: no
                Large Parallel I/O: no
                High-level library: no
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                   Build GIF Tools: no
                      Threadsafety: yes
               Default API mapping: v114
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib)
                     Map (H5M) API: no
                        Direct VFD: no
                        Mirror VFD: no
                     Subfiling VFD: no
                (Read-Only) S3 VFD: no
              (Read-Only) HDFS VFD: no
    Packages w/ extra debug output: AC,B2,CX,D,F,HL,I,O,S,T,Z
                       API tracing: yes
              Using memory checker: yes
            Function stack tracing: yes
                  Use file locking: best-effort
         Strict file format checks: yes
      Optimization instrumentation: no

### PR DESCRIPTION
**Pull request by derobins**
Fixes failures when running tests after building with thread-safety w/ code stacks on.

Fixes #2990

### CODE REVIEW

File: test/accum_swmr_reader.c [hunk 1]
```diff
@@ -35,24 +35,24 @@ const char *FILENAME[] = {"accum", "accum_swmr_big", NULL};
...
+    H5F_t   *f    = NULL;            /* File pointer */
     char     filename[1024];
     unsigned u;                      /* Local index variable */
     uint8_t  rbuf[1024];             /* Buffer for reading */
     uint8_t  buf[1024];              /* Buffer for holding the expected data */
     char    *driver         = NULL;  /* VFD string (from env variable) */
     hbool_t  api_ctx_pushed = FALSE; /* Whether API context pushed */
 
+    /* Testing setup */
+    h5_reset();
```
Comment (derobins) [inline test/accum_swmr_reader.c:54]: This is the real fix in this file (everything else is tidying)

File: test/swmr.c [hunk 2]
```diff
@@ -7728,12 +7728,15 @@ test_multiple_same(hid_t in_fapl, hbool_t new_format)
...
-    hbool_t file_locking_enabled = FALSE; /* Checks if the file system supports locks */
+    int     nerrors      = 0;               /* The # of errors */
+    hid_t   fapl         = H5I_INVALID_HID; /* File access property list ID */
+    char   *driver       = NULL;            /* VFD string (from env variable) */
+    char   *lock_env_var = NULL;            /* file locking env var pointer */
+    hbool_t use_file_locking;               /* read from env var */
+    hbool_t file_locking_enabled = FALSE;   /* Checks if the file system supports locks */
+
+    /* Testing setup */
+    h5_reset();
```
Comment (derobins) [inline test/swmr.c:7739]: This is the real fix in this file (everything else is tidying)

**Review by jhendersonHDF — APPROVED** [review]

**Review by byrnHDF — APPROVED** [review]
