### PR TITLE
Fix a heap buffer overflow during H5D__compact_readvv (GitHub #2606)

### LINKED ISSUE #2528: [BUG] Segmentation fault in H5MM.c in HDF5 v1.14.0
Segmentation fault in H5MM_memcpy at hdf5/src/H5MM.c in HDF5 v1.14.0

HDF5 version 1.14.0 - built from commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
```
export CC=clang
export CXX=clang++ 
export LDFLAGS="-lstdc++"
export ADDITIONAL="-g -fno-inline -fsanitize=address"
export LDFLAGS="$LDFLAGS -fsanitize=address"
export ASAN_OPTIONS=abort_on_error=1
CFLAGS="$ADDITIONAL" CXXFLAGS="$ADDITIONAL" ./configure --disable-shared
```
Command: ./h5dump POV
POV file: 
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013557/pov.zip)

Stack trace:

```
==2017054==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f1ed2066c59 bp 0x7ffcdc88e740 sp 0x7ffcdc88ded8 T0)
==2017054==The signal is caused by a READ memory access.
==2017054==Hint: address points to the zero page.
#0 0x7f1ed2066c59  /build/glibc-SzIz7B/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:345
#1 0x4c029f in __asan_memcpy /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
#2 0x80ae78 in H5MM_memcpy hdf5/src/H5MM.c:311:11
#3 0xb9e660 in H5VM_memcpyvv hdf5/src/H5VM.c:1610:13
#4 0xc62b77 in H5D__compact_readvv hdf5/src/H5Dcompact.c:350:26
#5 0x645b54 in H5D__select_io hdf5/src/H5Dselect.c:220:37
#6 0x644c27 in H5D__select_read hdf5/src/H5Dselect.c:465:9
#7 0xc66be1 in H5D__contig_read hdf5/src/H5Dcontig.c:850:13
#8 0x635d6f in H5D__read hdf5/src/H5Dio.c:369:17
#9 0xb81a93 in H5VL__native_dataset_read hdf5/src/H5VLnative_dataset.c:360:9
#10 0xb56b83 in H5VL__dataset_read hdf5/src/H5VLcallback.c:2047:9
#11 0xb568b6 in H5VL_dataset_read_direct hdf5/src/H5VLcallback.c:2090:9
#12 0x605d16 in H5D__read_api_common hdf5/src/H5D.c:1011:9
#13 0x605096 in H5Dread hdf5/src/H5D.c:1067:9
#14 0x53d4b0 in h5tools_dump_simple_dset hdf5/tools/lib/h5tools_dump.c:1758:17
#15 0x53bf7e in h5tools_dump_dset hdf5/tools/lib/h5tools_dump.c:1959:25
#16 0x534347 in h5tools_dump_data hdf5/tools/lib/h5tools_dump.c:4430:22
#17 0x5035e9 in dump_dataset hdf5/tools/src/h5dump/h5dump_ddl.c:1045:21
#18 0x4ffe2d in dump_all_cb hdf5/tools/src/h5dump/h5dump_ddl.c:349:21
#19 0x751262 in H5G__iterate_cb hdf5/src/H5Gint.c:865:25
#20 0x760355 in H5G__node_iterate hdf5/src/H5Gnode.c:966:25
#21 0xc27d36 in H5B__iterate_helper hdf5/src/H5B.c:1151:25
#22 0xc27955 in H5B_iterate hdf5/src/H5B.c:1193:22
#23 0x76e073 in H5G__stab_iterate hdf5/src/H5Gstab.c:535:26
#24 0x7663e8 in H5G__obj_iterate hdf5/src/H5Gobj.c:671:26
#25 0x750c8d in H5G_iterate hdf5/src/H5Gint.c:921:14
#26 0x7f3ebd in H5L_iterate hdf5/src/H5Lint.c:2246:22
#27 0xb8f198 in H5VL__native_link_specific hdf5/src/H5VLnative_link.c:366:38
#28 0xb667f3 in H5VL__link_specific hdf5/src/H5VLcallback.c:5482:22
#29 0xb665bd in H5VL_link_specific hdf5/src/H5VLcallback.c:5516:14
#30 0x7ea593 in H5L__iterate_api_common hdf5/src/H5L.c:1661:22
#31 0x7e9ee9 in H5Literate2 hdf5/src/H5L.c:1697:22
#32 0x50211f in dump_group hdf5/tools/src/h5dump/h5dump_ddl.c
#33 0x4fe5d6 in dump_all_cb hdf5/tools/src/h5dump/h5dump_ddl.c:228:25
#34 0x751262 in H5G__iterate_cb hdf5/src/H5Gint.c:865:25
#35 0x760355 in H5G__node_iterate hdf5/src/H5Gnode.c:966:25
#36 0xc27d36 in H5B__iterate_helper hdf5/src/H5B.c:1151:25
#37 0xc27955 in H5B_iterate hdf5/src/H5B.c:1193:22
#38 0x76e073 in H5G__stab_iterate hdf5/src/H5Gstab.c:535:26
#39 0x7663e8 in H5G__obj_iterate hdf5/src/H5Gobj.c:671:26
#40 0x750c8d in H5G_iterate hdf5/src/H5Gint.c:921:14
#41 0x7f3ebd in H5L_iterate hdf5/src/H5Lint.c:2246:22
#42 0xb8f198 in H5VL__native_link_specific hdf5/src/H5VLnative_link.c:366:38
#43 0xb667f3 in H5VL__link_specific hdf5/src/H5VLcallback.c:5482:22
#44 0xb665bd in H5VL_link_specific hdf5/src/H5VLcallback.c:5516:14
#45 0x7ea593 in H5L__iterate_api_common hdf5/src/H5L.c:1661:22
#46 0x7e9ee9 in H5Literate2 hdf5/src/H5L.c:1697:22
#47 0x50211f in dump_group hdf5/tools/src/h5dump/h5dump_ddl.c
#48 0x4f7723 in main hdf5/tools/src/h5dump/h5dump.c:1603:17
#49 0x7f1ed1fcf082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
#50 0x41c5ed in _start (hdf5/tools/src/h5dump/h5dump+0x41c5ed)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-SzIz7B/glibc-2.31/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:345
==2017054==ABORTING
```

### LINKED ISSUE #2606: [BUG] heap-buffer-overflow in H5MM_memcpy hdf5/src/H5MM.c
heap-buffer-overflow in H5MM_memcpy hdf5/src/H5MM.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11014102/pov.zip)

Stack trace:
```
==1948541==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000004a94 at pc 0x0000004c067a bp 0x7ffdddf77780 sp 0x7ffdddf76f30
READ of size 288 at 0x602000004a94 thread T0
#0 0x4c0679 in __asan_memcpy /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
#1 0x80ae78 in H5MM_memcpy hdf5/src/H5MM.c:311:11
#2 0xb9e660 in H5VM_memcpyvv hdf5/src/H5VM.c:1610:13
#3 0xc62b77 in H5D__compact_readvv hdf5/src/H5Dcompact.c:350:26
#4 0x645b54 in H5D__select_io hdf5/src/H5Dselect.c:220:37
#5 0x644c27 in H5D__select_read hdf5/src/H5Dselect.c:465:9
#6 0xc66be1 in H5D__contig_read hdf5/src/H5Dcontig.c:850:13
#7 0x635d6f in H5D__read hdf5/src/H5Dio.c:369:17
#8 0xb81a93 in H5VL__native_dataset_read hdf5/src/H5VLnative_dataset.c:360:9
#9 0xb56b83 in H5VL__dataset_read hdf5/src/H5VLcallback.c:2047:9
#10 0xb568b6 in H5VL_dataset_read_direct hdf5/src/H5VLcallback.c:2090:9
#11 0x605d16 in H5D__read_api_common hdf5/src/H5D.c:1011:9
#12 0x605096 in H5Dread hdf5/src/H5D.c:1067:9
#13 0x53d4b0 in h5tools_dump_simple_dset hdf5/tools/lib/h5tools_dump.c:1758:17
#14 0x53bf7e in h5tools_dump_dset hdf5/tools/lib/h5tools_dump.c:1959:25
#15 0x534347 in h5tools_dump_data hdf5/tools/lib/h5tools_dump.c:4430:22
#16 0x5035e9 in dump_dataset hdf5/tools/src/h5dump/h5dump_ddl.c:1045:21
#17 0x4ffe2d in dump_all_cb hdf5/tools/src/h5dump/h5dump_ddl.c:349:21
#18 0x751262 in H5G__iterate_cb hdf5/src/H5Gint.c:865:25
#19 0x760355 in H5G__node_iterate hdf5/src/H5Gnode.c:966:25
#20 0xc27d36 in H5B__iterate_helper hdf5/src/H5B.c:1151:25
#21 0xc27955 in H5B_iterate hdf5/src/H5B.c:1193:22
#22 0x76e073 in H5G__stab_iterate hdf5/src/H5Gstab.c:535:26
#23 0x7663e8 in H5G__obj_iterate hdf5/src/H5Gobj.c:671:26
#24 0x750c8d in H5G_iterate hdf5/src/H5Gint.c:921:14
#25 0x7f3ebd in H5L_iterate hdf5/src/H5Lint.c:2246:22
#26 0xb8f198 in H5VL__native_link_specific hdf5/src/H5VLnative_link.c:366:38
#27 0xb667f3 in H5VL__link_specific hdf5/src/H5VLcallback.c:5482:22
#28 0xb665bd in H5VL_link_specific hdf5/src/H5VLcallback.c:5516:14
#29 0x7ea593 in H5L__iterate_api_common hdf5/src/H5L.c:1661:22
#30 0x7e9ee9 in H5Literate2 hdf5/src/H5L.c:1697:22
#31 0x50211f in dump_group hdf5/tools/src/h5dump/h5dump_ddl.c
#32 0x4fe5d6 in dump_all_cb hdf5/tools/src/h5dump/h5dump_ddl.c:228:25
#33 0x751262 in H5G__iterate_cb hdf5/src/H5Gint.c:865:25
#34 0x760355 in H5G__node_iterate hdf5/src/H5Gnode.c:966:25
#35 0xc27d36 in H5B__iterate_helper hdf5/src/H5B.c:1151:25
#36 0xc27955 in H5B_iterate hdf5/src/H5B.c:1193:22
#37 0x76e073 in H5G__stab_iterate hdf5/src/H5Gstab.c:535:26
#38 0x7663e8 in H5G__obj_iterate hdf5/src/H5Gobj.c:671:26
#39 0x750c8d in H5G_iterate hdf5/src/H5Gint.c:921:14
#40 0x7f3ebd in H5L_iterate hdf5/src/H5Lint.c:2246:22
#41 0xb8f198 in H5VL__native_link_specific hdf5/src/H5VLnative_link.c:366:38
#42 0xb667f3 in H5VL__link_specific hdf5/src/H5VLcallback.c:5482:22
#43 0xb665bd in H5VL_link_specific hdf5/src/H5VLcallback.c:5516:14
#44 0x7ea593 in H5L__iterate_api_common hdf5/src/H5L.c:1661:22
#45 0x7e9ee9 in H5Literate2 hdf5/src/H5L.c:1697:22
#46 0x50211f in dump_group hdf5/tools/src/h5dump/h5dump_ddl.c
#47 0x4f7723 in main hdf5/tools/src/h5dump/h5dump.c:1603:17
#48 0x7fb1d89fe082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
#49 0x41c5ed in _start (hdf5/tools/src/h5dump/h5dump+0x41c5ed)
0x602000004a94 is located 0 bytes to the right of 4-byte region [0x602000004a90,0x602000004a94)
allocated by thread T0 here:
#0 0x4c170f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x86a081 in H5O__layout_copy hdf5/src/H5Olayout.c:784:60
#2 0x8732df in H5O_msg_read hdf5/src/H5Omessage.c:454:30
#3 0x63d2e7 in H5D__layout_oh_read hdf5/src/H5Dlayout.c:618:17
#4 0x623906 in H5D_open hdf5/src/H5Dint.c:1498:13
#5 0x622d37 in H5D__open_name hdf5/src/H5Dint.c:1433:25
#6 0xb81750 in H5VL__native_dataset_open hdf5/src/H5VLnative_dataset.c:318:25
#7 0xb5638b in H5VL__dataset_open hdf5/src/H5VLcallback.c:1946:30
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3 in __asan_memcpy
Shadow bytes around the buggy address:
0x0c047fff8900: fa fa 00 fa fa fa 00 01 fa fa fd fa fa fa fd fa
0x0c047fff8910: fa fa 00 fa fa fa 01 fa fa fa 00 04 fa fa fd fd
0x0c047fff8920: fa fa fd fd fa fa fd fa fa fa 00 fa fa fa fd fa
0x0c047fff8930: fa fa 00 fa fa fa 00 fa fa fa fd fa fa fa 00 fa
0x0c047fff8940: fa fa 00 fa fa fa 00 fa fa fa fd fa fa fa 00 fa
=>0x0c047fff8950: fa fa[04]fa fa fa 04 fa fa fa 00 00 fa fa fd fa
0x0c047fff8960: fa fa 00 fa fa fa 00 fa fa fa 00 00 fa fa 00 fa
0x0c047fff8970: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
0x0c047fff8980: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa fa fa
0x0c047fff8990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c047fff89a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable:           00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone:       fa
Freed heap region:       fd
Stack left redzone:      f1
Stack mid redzone:       f2
Stack right redzone:     f3
Stack after return:      f5
Stack use after scope:   f8
Global redzone:          f9
Global init order:       f6
Poisoned by user:        f7
Container overflow:      fc
Array cookie:            ac
Intra object redzone:    bb
ASan internal:           fe
Left alloca redzone:     ca
Right alloca redzone:    cb
Shadow gap:              cc
==1948541==ABORTING
```

### PR DESCRIPTION
**Pull request by jhendersonHDF**

### CODE REVIEW

File: src/H5Dint.c [hunk 1]
```diff
@@ -1718,6 +1718,33 @@ H5D__open_oid(H5D_t *dataset, hid_t dapl_id)
...
+        size_t   dset_data_size = 0;
+
+        HDassert(H5D_COMPACT == dataset->shared->layout.storage.type);
+
+        if ((dset_nelemts = H5S_GET_EXTENT_NPOINTS(dataset->shared->space)) < 0)
+            HGOTO_ERROR(H5E_DATASET, H5E_CANTGET, FAIL, "can't get number of elements in dataset's dataspace")
+
+        dset_data_size = (size_t)dset_nelemts * dset_type_size;
+
+        if (dataset->shared->layout.storage.u.compact.size != dset_data_size)
```
Comment (mattjala) [inline src/H5Dint.c:1742]: Does the library allow users to create files with headers that allocate more memory than strictly necessary? If so, this could throw errors on well-formed datasets.

Comment (jhendersonHDF) [reply src/H5Dint.c:1742]: The library calculates the size of the compact data buffer by the same process of multiplying the number of dataset elements by the size of the dataset's datatype and then encodes that into the file, so a dataset header in a well-formed file should always (at least currently) match exactly with the size of the dataset's data.

**Review by mattjala — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]
