### PR TITLE
Fix issues with empty or uninitialized link names

### LINKED ISSUE #4307: use-of-uninitialized-value error in H5G__ent_to_link
**Describe the bug**

use-of-uninitialized-value
         # 0 0xaef255 in H5G__ent_to_link [hdf5/src/H5Gent.c:408](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Gent.c#L408):13
	    # 1 0xb14ded in H5G__node_iterate [hdf5/src/H5Gnode.c:934](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Gnode.c#L934):17
	    # 2 0x14a0e15 in H5B__iterate_helper [hdf5/src/H5B.c:1088](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5B.c#L1088):25
	    # 3 0x14a0553 in H5B_iterate [hdf5/src/H5B.c:1127](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5B.c#L1127):22
	    # 4 0xb2fdaa in H5G__stab_iterate [hdf5/src/H5Gstab.c:504](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Gstab.c#L504):26
	    # 5 0xb21807 in H5G__obj_iterate [hdf5/src/H5Gobj.c:664](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Gobj.c#L664):26
	    # 6 0xaf5545 in H5G_iterate [hdf5/src/H5Gint.c:869](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Gint.c#L869):14
	    # 7 0xc2c073 in H5L_iterate [hdf5/src/H5Lint.c:2148](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5Lint.c#L2148):22
	    # 8 0x13b0b1a in H5VL__native_link_specific [hdf5/src/H5VLnative_link.c:364](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5VLnative_link.c#L364):38
	    # 9 0x135f815 in H5VL__link_specific [hdf5/src/H5VLcallback.c:5482](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5VLcallback.c#L5482):22
	    # 10 0x135f815 in H5VL_link_specific [hdf5/src/H5VLcallback.c:5516](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5VLcallback.c#L5516):14
	    # 11 0xc1a751 in H5L__iterate_api_common [hdf5/src/H5L.c:1610](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5L.c#L1610):22
	    # 12 0xc19aa5 in H5Literate2 [hdf5/src/H5L.c:1646](https://github.com/HDFGroup/hdf5/blob/9f7b987a4fc2379fa93917be55339fbfe716975c/src/H5L.c#L1646):22

**Additional context**

Reported for 9f7b987a4fc2379fa93917be55339fbfe716975c.

Can likely be fixed by setting `lnk->name = NULL;` in the called function H5G__ent_to_link or by initializing `lnk.name = NULL;` (and probably other struct members) in the calling function H5G__node_iterate. Not sure what you prefer and if there are similar cases in the lib.

Introduced by merging #4283 -> relevant for v1.14.4.

### PR DESCRIPTION
**Pull request by jhendersonHDF**
Converts an assertion in H5G_loc_find into a normal error check that checks for empty link names

Initializes H5O_link_t structure early in H5G__ent_to_link to avoid trying to free potentially uninitialized memory

Checks for an empty link name after H5MM_strndup in H5G__ent_to_link

Fixes GitHub #4307

### CODE REVIEW

File: src/H5Gloc.c [hunk 1]
```diff
@@ -410,9 +410,12 @@ H5G_loc_find(const H5G_loc_t *loc, const char *name, H5G_loc_t *obj_loc /*out*/)
 
     /* Check args. */
     assert(loc);
-    assert(name && *name);
```
Comment (jhendersonHDF) [inline src/H5Gloc.c:413]: This was failing in debug builds due to the assertion on `*name`, but would pass for release/production builds. That said, I don't think it's allowed to have an empty link name for an object, so I converted this to a regular error check.

**Comment by jhendersonHDF** [comment]
This fixes the current CVE testing. It doesn't appear to be a missed issue, but rather a new issue that was masked by previous CVE problems.

**Review by lrknox — APPROVED** [review]

**Review by byrnHDF — APPROVED** [review]
