### PR TITLE
Take user block into account when returning chunk addresses

### LINKED ISSUE #3003: H5Dchunk_iter() does not account for user block when reporting chunk file address
#### Describe the bug

For HDF5 files with user block the `H5Dchunk_iter()` function does not account for user block size when reporting chunk file address. To correct this one has to add user block size to locate the actual chunk in that file. The function's documentation does not mention this.

The function for contiguous datasets, `H5Dget_offset()`, does correctly take into account user block size.

#### Expected behavior

`H5Dchunk_iter()` should report chunk file addresses corrected for user block size if present. The documentation for the libhdf5 releases with this function should have a note to alert users.

#### Platform (please complete the following information)

 - HDF5 version: 1.14.0
 - OS: AWS EC2 Linux
 - Compiler and version: N/A
 - Build system: obtained with the `conda` package manager from the conda-forge channel
 - Any configure options you specified: N/A
 - No MPI or parallel build

#### Additional context

Sample files attached:
* A file with one contiguous and one chunked dataset. [test.h5.zip](https://github.com/HDFGroup/hdf5/files/11549732/test.h5.zip)
* A copy of the above file but with a 4,096 bytes user block. [ublock4kiB_test.h5.zip](https://github.com/HDFGroup/hdf5/files/11549733/ublock4kiB_test.h5.zip)

The chunk file addresses from both files will be the same.

### PR DESCRIPTION
**Pull request by derobins**
Both H5Dchunk_iter() and H5Dget_chunk_info(_by_coord)() did not take the size of the user block into account when reporting addresses. Since the #1 use of these functions is to root around in the file for the raw data, this is kind of a problem.

Fixes GitHub issue #3003

### CODE REVIEW

File: src/H5Dchunk.c
Comment (derobins) [inline src/H5Dchunk.c:1]: There's a lot of cleanup in this file. The new test and its helper functions are at the end.

File: test/chunk_info.c
Comment (derobins) [inline test/chunk_info.c:1]: There's a lot of cleanup in this file. The new test and its helper function are at the end.

File: src/H5Dchunk.c [hunk 1]
```diff
@@ -8115,33 +8118,32 @@ H5D__get_chunk_info_by_coord(const H5D_t *dset, const hsize_t *offset, unsigned
...
+        offset[i] = chunk_rec->scaled[i] * chunk->dim[i];
 
     FUNC_ENTER_PACKAGE_NOERR
 
     /* Check for callback failure and pass along return value */
-    if ((ret_value = (data->op)(offset, (unsigned)chunk_rec->filter_mask, chunk_rec->chunk_addr,
-                                (hsize_t)chunk_rec->nbytes, data->op_data)) < 0)
+    if ((ret_value =
+             (data->op)(offset, (unsigned)chunk_rec->filter_mask, data->base_addr + chunk_rec->chunk_addr,
+                        (hsize_t)chunk_rec->nbytes, data->op_data)) < 0)
```
Comment (derobins) [inline src/H5Dchunk.c:8146]: H5Dchunk_iter() fix here

File: src/H5Dchunk.c [hunk 2]
```diff
@@ -8196,14 +8196,15 @@ H5D__chunk_iter(H5D_t *dset, H5D_chunk_iter_op_t op, void *op_data)
         H5D_chunk_iter_ud_t ud;
 
         /* Set up info for iteration callback */
-        ud.op      = op;
-        ud.op_data = op_data;
-        ud.chunk   = &dset->shared->layout.u.chunk;
+        ud.op        = op;
+        ud.op_data   = op_data;
+        ud.chunk     = &dset->shared->layout.u.chunk;
+        ud.base_addr = H5F_BASE_ADDR(dset->oloc.file);
```
Comment (derobins) [inline src/H5Dchunk.c:8202]: H5Dchunk_iter() fix here

File: src/H5Dchunk.c [hunk 3]
```diff
@@ -8102,11 +8105,11 @@ H5D__get_chunk_info_by_coord(const H5D_t *dset, const hsize_t *offset, unsigned
             if (filter_mask)
                 *filter_mask = udata.filter_mask;
             if (addr)
-                *addr = udata.chunk_addr;
+                *addr = udata.chunk_addr + H5F_BASE_ADDR(dset->oloc.file);
```
Comment (derobins) [inline src/H5Dchunk.c:8108]: H5Dget_chunk_info_by_coord() fix

File: src/H5Dchunk.c [hunk 4]
```diff
@@ -7967,14 +7968,14 @@ H5D__get_chunk_info(const H5D_t *dset, const H5S_t H5_ATTR_UNUSED *space, hsize_
...
```
Comment (derobins) [inline src/H5Dchunk.c:7971]: H5Dget_chunk_info() fix

File: test/chunk_info.c [hunk 5]
```diff
@@ -2180,17 +2118,312 @@ test_flt_msk_with_skip_compress(hid_t fapl)
...
+            TEST_ERROR;
+        if (HDread(fd_ub, &data_ub, sizeof(int)) != sizeof(int))
+            TEST_ERROR;
+
+        if (data != data_ub)
+            TEST_ERROR;
+    }
+
+    HDclose(fd);
+    HDclose(fd_ub);
```
Comment (jhendersonHDF) [inline test/chunk_info.c:2377]: Not a big deal, but reset FDs to -1 in case below closes fail and try to do the close again.

File: test/chunk_info.c [hunk 6]
```diff
@@ -2180,17 +2118,312 @@ test_flt_msk_with_skip_compress(hid_t fapl)
...
+    if (H5Fclose(fid) < 0)
+        TEST_ERROR;
+    if (H5Fclose(fid_ub) < 0)
+        TEST_ERROR;
+
+    free(addresses);
+    free(addresses_ub);
+
+    HDremove(UBLOCK_FILE_NAME);
+    HDremove(NO_UBLOCK_FILE_NAME);
```
Comment (jhendersonHDF) [inline test/chunk_info.c]: Can use `H5Fdelete` here for compatibility

**Review by jhendersonHDF — APPROVED** [review]

**Review by qkoziol — APPROVED** [review]

**Comment by fortnern** [comment]
Are there other places in the code that do take the user block into account when returning addresses?

**Comment by fortnern** [comment]
> Are there other places in the code that do take the user block into account when returning addresses?

It looks like H5Dget_offset does take the user block into account, but H5Oget_info3 does not, perhaps because it returns a "token" instead of an address

**Review by fortnern — APPROVED** [review]
