### PR TITLE
Fix for github issue #2414: segfault when copying dataset with attrib…

### LINKED ISSUE #3214: Segfault when copying dataset
**Describe the bug**
I have created an HDF5 file with h5py that contains a compound dataset which cannot be copied (not using `h5py.h5o.copy` and not using the `h5copy` program). I get a Segmentation fault.

The interesting point here is, that I can create a new HDF5 file `input2.h5` with an identical dataset which can be copied. When I look at the two input files `input.h5` and `input2.h5` with HDFView, the only difference I see is the object ref.

Here are the data files (`output.h5` is just an empty file for your convenience).
[h5copy_compound.zip](https://github.com/HDFGroup/hdf5/files/11914414/h5copy_compound.zip)

```bash
# This works:
$ h5copy -i input.h5 -o output.h5 -s "/events/frame" -d "/frame"
# This causes a segmentation fault:
$ h5copy -i input.h5 -o output.h5 -s "/tables/cytoshot_monitor" -d "/monitor"
Segmentation fault
# But this works with a dataset containing the same `cytoshot_monitor` information as input.h5:
$ h5copy -i input2.h5 -o output.h5 -s "/tables/cytoshot_monitor" -d "/monitor"
```

Possibly related issue: https://github.com/HDFGroup/hdf5/issues/2414 (But here it is not related to attributes I think).

**Expected behavior**
Performing h5copy does not segfault.

**Platform (please complete the following information)**
 - HDF5 version:
```
Summary of the h5py configuration
---------------------------------

h5py    3.8.0
HDF5    1.12.2
Python  3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.23.5
cython (built with) 0.29.33
numpy (built against) 1.21.6
HDF5 (built against) 1.12.2
```
 - OS and version Ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by vchoi-hdfgroup**
…utes.

This also fixes github issue #3241: segfault when copying dataset. Need to set the location via H5T_set_loc() of the src datatype when copying dense attributes.
Otherwise the vlen callbacks are not set up therefore causing seg fault when doing H5T_convert() -> H5T__conv_vlen().

### CODE REVIEW

**Comment by mattjala** [comment]
I think issue #3214 is the one you meant to link - 3241 seems unrelated.

File: src/H5Aint.c [hunk 1]
```diff
@@ -2456,6 +2456,10 @@ H5A__dense_post_copy_file_cb(const H5A_t *attr_src, void *_udata)
     assert(udata->file);
     assert(udata->cpy_info);
 
+    /* Set the location of the src datatype */
+    if (H5T_set_loc(attr_src->shared->dt, H5F_VOL_OBJ(udata->oloc_src->file), H5T_LOC_DISK) < 0)
+        HGOTO_ERROR(H5E_DATATYPE, H5E_CANTINIT, FAIL, "cannot mark datatype on disk");
```
Comment (jhendersonHDF) [inline src/H5Aint.c]: Even though they're the same value, looks like this should probably be `H5_ITER_ERROR` rather than `FAIL`, along with the other `FAIL`s in this function. Otherwise, looks good to me.

**Comment by vchoi-hdfgroup** [comment]
> I think issue #3214 is the one you meant to link - 3241 seems unrelated.

You are right!

File: src/H5Aint.c (hunk 1 above)
Comment (vchoi-hdfgroup) [reply src/H5Aint.c]: Fixed

**Review by jhendersonHDF — APPROVED** [review]

**Review by lrknox — APPROVED** [review]
