### PR TITLE
Fix memory leaks when processing OH cont messages

### LINKED ISSUE #2604: [BUG] heap-buffer-overflow in H5F_addr_decode_len hdf5/src/H5Fint.c
heap-buffer-overflow in H5F_addr_decode_len hdf5/src/H5Fint.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013625/pov.zip)

Stack trace:
```
==1948178==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060000053f8 at pc 0x0000006b5674 bp 0x7ffdb38e8e10 sp 0x7ffdb38e8e08
READ of size 1 at 0x6060000053f8 thread T0
#0 0x6b5673 in H5F_addr_decode_len hdf5/src/H5Fint.c:2859:13
#1 0x833586 in H5O__cont_decode hdf5/src/H5Ocont.c:103:5
#2 0x830186 in H5O__chunk_deserialize hdf5/src/H5Ocache.c:1513:38
#3 0x82abf3 in H5O__cache_deserialize hdf5/src/H5Ocache.c:335:9
#4 0x5c990a in H5C__load_entry hdf5/src/H5C.c:7298:26
#5 0x5c6b0d in H5C_protect hdf5/src/H5C.c:2330:30
#6 0x58386f in H5AC_protect hdf5/src/H5AC.c:1394:26
#7 0x85c0a6 in H5O_protect hdf5/src/H5Oint.c:1045:32
#8 0x874619 in H5O_msg_exists hdf5/src/H5Omessage.c:843:23
#9 0x76a2a9 in H5G_mkroot hdf5/src/H5Groot.c:226:32
#10 0x6ab661 in H5F_open hdf5/src/H5Fint.c:1973:13
#11 0xb86ba5 in H5VL__native_file_open hdf5/src/H5VLnative_file.c:127:29
#12 0xb5ea08 in H5VL__file_open hdf5/src/H5VLcallback.c:3674:30
#13 0xb5e421 in H5VL_file_open hdf5/src/H5VLcallback.c:3823:30
#14 0x693a1d in H5F__open_api_common hdf5/src/H5F.c:794:29
#15 0x693287 in H5Fopen hdf5/src/H5F.c:835:22
#16 0x52641d in h5tools_fopen hdf5/tools/lib/h5tools.c:973:19
#17 0x4f7182 in main hdf5/tools/src/h5dump/h5dump.c:1477:19
#18 0x7f257b7f2082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
#19 0x41c5ed in _start (hdf5/tools/src/h5dump/h5dump+0x41c5ed)
0x6060000053f8 is located 0 bytes to the right of 56-byte region [0x6060000053c0,0x6060000053f8)
allocated by thread T0 here:
#0 0x4c170f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x72cebb in H5FL__malloc hdf5/src/H5FL.c:237:30
#2 0x82abf3 in H5O__cache_deserialize hdf5/src/H5Ocache.c:335:9
SUMMARY: AddressSanitizer: heap-buffer-overflow hdf5/src/H5Fint.c:2859:13 in H5F_addr_decode_len
Shadow bytes around the buggy address:
0x0c0c7fff8a20: fa fa fa fa 00 00 00 00 00 00 00 fa fa fa fa fa
0x0c0c7fff8a30: 00 00 00 00 00 00 00 fa fa fa fa fa 00 00 00 00
0x0c0c7fff8a40: 00 00 00 fa fa fa fa fa 00 00 00 00 00 00 00 00
0x0c0c7fff8a50: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
0x0c0c7fff8a60: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
=>0x0c0c7fff8a70: 00 00 00 fa fa fa fa fa 00 00 00 00 00 00 00[fa]
0x0c0c7fff8a80: fa fa fa fa 00 00 00 00 00 00 00 fa fa fa fa fa
0x0c0c7fff8a90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c0c7fff8aa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c0c7fff8ab0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x0c0c7fff8ac0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable:           00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone:       fa
Freed heap region:       fd
Stack left redzone:      f1
Stack mid redzone:       f2
Stack right redzone:     f3
Stack after return:      f5
Stack use after scope:   f8
Global redzone:          f9
Global init order:       f6
Poisoned by user:        f7
Container overflow:      fc
Array cookie:            ac
Intra object redzone:    bb
ASan internal:           fe
Left alloca redzone:     ca
Right alloca redzone:    cb
Shadow gap:              cc
==1948178==ABORTING
```

### PR DESCRIPTION
**Pull request by derobins**
Malformed object header continuation messages can result in a too-small buffer being passed to the decode function, which could lead to reading past the end of the buffer. Additionally, errors in processing these malformed messages can lead to allocated memory not being cleaned up.

This fix adds bounds checking and cleanup code to the object header continuation message processing.

Fixes #2604

### CODE REVIEW

File: src/H5Ocont.c [hunk 1]
```diff
@@ -74,32 +74,29 @@ H5FL_DEFINE(H5O_cont_t);
...
     /* Allocate space for the message */
     if (NULL == (cont = H5FL_MALLOC(H5O_cont_t)))
-        HGOTO_ERROR(H5E_RESOURCE, H5E_NOSPACE, NULL, "memory allocation failed");
+        HGOTO_ERROR(H5E_OHDR, H5E_NOSPACE, NULL, "memory allocation failed");
 
     /* Decode */
+    if (H5_IS_BUFFER_OVERFLOW(p, H5F_sizeof_addr(f), p_end))
+        HGOTO_ERROR(H5E_OHDR, H5E_OVERFLOW, NULL, "ran off end of input buffer while decoding");
     H5F_addr_decode(f, &p, &(cont->addr));
     H5F_DECODE_LENGTH(f, p, cont->size);
```
Comment (jhendersonHDF) [inline src/H5Ocont.c:104]: Looks like another buffer check is needed for this call to H5F_DECODE_LENGTH or `cont->size` should be added to the computed length in the check above.

Comment (derobins) [reply src/H5Ocont.c:104]: Oops! Fixed.

**Review by jhendersonHDF — APPROVED** [review]

**Review by hyoklee — APPROVED** [review]
